env {
  parallelism = 1
  job.mode = "BATCH"
}

source {
  Jdbc {
    url = "jdbc:mysql://host.docker.internal:3307/dataweave_biz?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
    driver = "com.mysql.cj.jdbc.Driver"
    user = "biz"
    password = "biz"
    query = "SELECT id, name, val FROM seatunnel_source"
    result_table_name = "jdbc_source"
  }
}

sink {
  Jdbc {
    url = "jdbc:mysql://host.docker.internal:3307/dataweave_biz?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
    driver = "com.mysql.cj.jdbc.Driver"
    user = "biz"
    password = "biz"
    query = "INSERT INTO seatunnel_sink (id, name, val) VALUES (?, ?, ?)"
    source_table_name = "jdbc_source"
  }
}
