env {
  parallelism = 1
  job.mode = "BATCH"
}

source {
  FakeSource {
    row.num = 5
    schema = {
      fields {
        name = "string"
        age = "int"
        score = "double"
      }
    }
    result_table_name = "fake"
  }
}

sink {
  Console {
    source_table_name = "fake"
  }
}
