package com.dataweave.master.companion.infrastructure;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.atomic.AtomicInteger;

import javax.sql.DataSource;

import com.dataweave.master.companion.domain.PatrolRun;
import com.dataweave.master.companion.domain.PatrolRunStates;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.SingleConnectionDataSource;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * 巡检调度并发安全测试（T032）：真多连接并发验证分布式不变量——
 * ① arm：多"master"并发 tryClaimCreate 同一 fire_time → UNIQUE 单赢，只一条 run（无重复）；
 * ② claim：并发 casStart 同一 CLAIMED run → CAS 单转，只一条 RUNNING（无 double-claim/straggler）。
 *
 * <p>每线程独立 {@link SingleConnectionDataSource} 连同一 in-memory H2（DB_CLOSE_DELAY=-1 跨连接共享），
 * 真实并发而非单连接串行。这是双 master 分布式安全的 DB 地基（UNIQUE + SKIP LOCKED + CAS），
 * 真正的 2-JVM 双实例端到端由集成/部署期回归门覆盖（CLAUDE.md 调度路径验证要求）。
 */
class PatrolSchedulerConcurrencyTest {

    private static final String URL =
            "jdbc:h2:mem:companion_concur;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;" +
            "DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;LOCK_TIMEOUT=10000";
    private static final int MASTERS = 16;

    private DataSource ds;
    private JdbcTemplate jdbc;

    @BeforeEach
    void setUp() {
        ds = new SingleConnectionDataSource(URL, true);
        jdbc = new JdbcTemplate(ds);
        jdbc.execute("""
                CREATE TABLE patrol_routine (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id BIGINT NOT NULL, project_id BIGINT NOT NULL,
                    domain VARCHAR(32) NOT NULL, enabled SMALLINT NOT NULL DEFAULT 1,
                    cron_expression VARCHAR(64) NOT NULL, scope_json TEXT,
                    timeout_seconds INTEGER NOT NULL DEFAULT 120,
                    created_by BIGINT, updated_by BIGINT,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    deleted SMALLINT NOT NULL DEFAULT 0, version INTEGER NOT NULL DEFAULT 0)
                """);
        jdbc.execute("""
                CREATE TABLE patrol_run (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id BIGINT NOT NULL, project_id BIGINT NOT NULL,
                    routine_id BIGINT NOT NULL, trigger_type VARCHAR(16) NOT NULL,
                    scheduled_fire_time TIMESTAMP NOT NULL, state VARCHAR(16) NOT NULL DEFAULT 'CLAIMED',
                    started_at TIMESTAMP, finished_at TIMESTAMP, summary TEXT, error TEXT,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    version INTEGER NOT NULL DEFAULT 0,
                    CONSTRAINT uk_patrol_run_routine_fire UNIQUE (routine_id, scheduled_fire_time))
                """);
        jdbc.update("INSERT INTO patrol_routine (tenant_id, project_id, domain, cron_expression) VALUES (1,1,'TASK_FAILURE','0 0 * * * *')");
    }

    @AfterEach
    void tearDown() {
        jdbc.execute("DROP ALL OBJECTS");
        ((SingleConnectionDataSource) ds).destroy();
    }

    /** 每个 master 自己的连接 + run 仓储。 */
    private static JdbcPatrolRunRepository repoOnOwnConnection() {
        return new JdbcPatrolRunRepository(new JdbcTemplate(new SingleConnectionDataSource(URL, true)));
    }

    @Test
    void concurrentArm_uniqueSingleWinner_noDuplicateRun() throws Exception {
        long routineId = 1L;
        LocalDateTime fire = LocalDateTime.of(2026, 7, 15, 9, 0);
        ExecutorService pool = Executors.newFixedThreadPool(MASTERS);
        CountDownLatch ready = new CountDownLatch(MASTERS);
        CountDownLatch fireGun = new CountDownLatch(1);
        AtomicInteger winners = new AtomicInteger();
        List<Future<Optional<PatrolRun>>> futures = new ArrayList<>();

        for (int i = 0; i < MASTERS; i++) {
            futures.add(pool.submit(() -> {
                JdbcPatrolRunRepository repo = repoOnOwnConnection();
                ready.countDown();
                fireGun.await();
                Optional<PatrolRun> r = repo.tryClaimCreate(1L, 1L, routineId, "SCHEDULED", fire);
                if (r.isPresent()) winners.incrementAndGet();
                return r;
            }));
        }
        ready.await();
        fireGun.countDown();   // 同时开抢
        pool.shutdown();
        for (Future<Optional<PatrolRun>> f : futures) f.get();

        // UNIQUE 单赢：16 个 master 并发，只 1 个 INSERT 成功（其余撞键放弃）
        assertThat(winners.get()).isEqualTo(1);
        Integer runCount = jdbc.queryForObject(
                "SELECT COUNT(*) FROM patrol_run WHERE routine_id = ? AND scheduled_fire_time = ?",
                Integer.class, routineId, fire);
        assertThat(runCount).isEqualTo(1);   // 无重复 run
    }

    @Test
    void concurrentClaim_casSingleTransition_noDoubleClaim() throws Exception {
        // 先 arm 一条 CLAIMED run
        long runId = repoOnOwnConnection()
                .tryClaimCreate(1L, 1L, 1L, "SCHEDULED", LocalDateTime.of(2026, 7, 15, 10, 0))
                .orElseThrow().id();

        ExecutorService pool = Executors.newFixedThreadPool(MASTERS);
        CountDownLatch ready = new CountDownLatch(MASTERS);
        CountDownLatch fireGun = new CountDownLatch(1);
        AtomicInteger transitions = new AtomicInteger();
        List<Future<Boolean>> futures = new ArrayList<>();

        for (int i = 0; i < MASTERS; i++) {
            futures.add(pool.submit(() -> {
                JdbcPatrolRunRepository repo = repoOnOwnConnection();
                ready.countDown();
                fireGun.await();
                boolean ok = repo.casStart(runId);   // CAS CLAIMED→RUNNING
                if (ok) transitions.incrementAndGet();
                return ok;
            }));
        }
        ready.await();
        fireGun.countDown();
        pool.shutdown();
        for (Future<Boolean> f : futures) f.get();

        // CAS 单转：16 并发，只 1 个 CLAIMED→RUNNING 成功（其余 state 已变 → WHERE state=CLAIMED 失败）
        assertThat(transitions.get()).isEqualTo(1);
        assertThat(jdbc.queryForObject("SELECT state FROM patrol_run WHERE id = ?", String.class, runId))
                .isEqualTo(PatrolRunStates.RUNNING);   // 无 double-claim，无 straggler
    }
}
