package com.dataweave.master.companion.infrastructure;

import java.util.function.Consumer;

import javax.sql.DataSource;

import com.dataweave.master.companion.application.CompanionBrainSelector;
import com.dataweave.master.companion.application.CompanionBriefingService;
import com.dataweave.master.companion.application.CompanionEventPublisher;
import com.dataweave.master.companion.application.CompanionStateResolver;
import com.dataweave.master.companion.application.CompanionTurnRegistry;
import com.dataweave.master.companion.application.PatrolService;
import com.dataweave.master.companion.domain.CompanionBrain;
import com.dataweave.master.companion.domain.PatrolRunStates;
import com.dataweave.master.domain.EventBus;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.SingleConnectionDataSource;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * PatrolScheduler 调度幂等测试（T021）：同一 fire_time 即使 arm 多次也只产一条 CLAIMED run
 * （UNIQUE 单赢，调度不变量①）；claim 把 CLAIMED 推进到 RUNNING。无真 workhorse。
 */
class PatrolSchedulerTest {

    private static final long TENANT = 1L;
    private static final long PROJECT = 1L;

    private DataSource ds;
    private JdbcTemplate jdbc;
    private JdbcPatrolRoutineRepository routineRepo;
    private JdbcPatrolRunRepository runRepo;
    private PatrolScheduler scheduler;

    @BeforeEach
    void setUp() {
        ds = new SingleConnectionDataSource(
                "jdbc:h2:mem:companion_sched_it;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;" +
                "DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE", true);
        jdbc = new JdbcTemplate(ds);
        jdbc.execute("""
                CREATE TABLE patrol_routine (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id BIGINT NOT NULL, project_id BIGINT NOT NULL,
                    domain VARCHAR(32) NOT NULL, enabled SMALLINT NOT NULL DEFAULT 1,
                    cron_expression VARCHAR(64) NOT NULL, scope_json TEXT,
                    timeout_seconds INTEGER NOT NULL DEFAULT 120,
                    created_by BIGINT, updated_by BIGINT,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    deleted SMALLINT NOT NULL DEFAULT 0, version INTEGER NOT NULL DEFAULT 0)
                """);
        jdbc.execute("""
                CREATE TABLE patrol_run (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id BIGINT NOT NULL, project_id BIGINT NOT NULL,
                    routine_id BIGINT NOT NULL, trigger_type VARCHAR(16) NOT NULL,
                    scheduled_fire_time TIMESTAMP NOT NULL, state VARCHAR(16) NOT NULL DEFAULT 'CLAIMED',
                    started_at TIMESTAMP, finished_at TIMESTAMP, summary TEXT, error TEXT,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    version INTEGER NOT NULL DEFAULT 0)
                """);
        jdbc.execute("""
                CREATE TABLE patrol_report (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id BIGINT NOT NULL, project_id BIGINT NOT NULL,
                    run_id BIGINT, domain VARCHAR(32) NOT NULL, severity VARCHAR(16) NOT NULL,
                    title VARCHAR(255) NOT NULL, summary TEXT, detail_json TEXT,
                    aggregate_count INTEGER NOT NULL DEFAULT 1, status VARCHAR(16) NOT NULL DEFAULT 'UNREAD',
                    closed_by VARCHAR(128), closed_at TIMESTAMP,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)
                """);
        routineRepo = new JdbcPatrolRoutineRepository(jdbc);
        JdbcPatrolRunRepository runRepo = new JdbcPatrolRunRepository(jdbc);
        JdbcPatrolReportRepository reportRepo = new JdbcPatrolReportRepository(jdbc);
        this.runRepo = runRepo;
        EventBus fakeBus = new EventBus() {
            @Override public void publish(String channel, String message) {}
            @Override public Subscription subscribe(String channel, Consumer<String> handler) { return () -> {}; }
        };
        CompanionEventPublisher publisher = new CompanionEventPublisher(fakeBus);
        CompanionBrainSelector selector = new CompanionBrainSelector(null, null) {
            @Override public CompanionBrain forPatrol() { return new com.dataweave.master.companion.infrastructure.MockBrain(); }
        };
        PatrolService patrolService = new PatrolService(runRepo, routineRepo, reportRepo, selector, publisher,
                new CompanionStateResolver(reportRepo, runRepo, new CompanionTurnRegistry(), publisher),
                new CompanionBriefingService(runRepo, reportRepo, routineRepo, publisher), 1);
        scheduler = new PatrolScheduler(routineRepo, runRepo, patrolService,
                new DataSourceTransactionManager(ds), true, 10);
    }

    @AfterEach
    void tearDown() {
        jdbc.execute("DROP ALL OBJECTS");
        ((SingleConnectionDataSource) ds).destroy();
    }

    @Test
    void arm_isIdempotent_sameFireTimeArmedOnce() {
        // 每小时 :00 的 cron——槽位在测试期内稳定（不跨小时边界），便于断言"只一条"
        long routineId = routineRepo.insert(TENANT, PROJECT, "TASK_FAILURE", true, "0 0 * * * *", null, 120, 1L);

        scheduler.armTick();   // 首次 arm：到点的最近 fire_time 落一条 CLAIMED
        assertThat(runRepo.findByRoutine(routineId, 10)).hasSize(1);
        assertThat(runRepo.findByRoutine(routineId, 10).get(0).state()).isEqualTo(PatrolRunStates.CLAIMED);

        // 再次 arm：同一 fire_time 已存在，UNIQUE 单赢 → 不新增（调度不变量①幂等）
        scheduler.armTick();
        scheduler.armTick();
        assertThat(runRepo.findByRoutine(routineId, 10)).hasSize(1);
    }

    @Test
    void arm_skipsDisabledRoutines() {
        routineRepo.insert(TENANT, PROJECT, "MACHINE", false, "0 0 * * * *", null, 120, 1L);  // disabled
        scheduler.armTick();
        assertThat(runRepo.findByRoutine(routineRepo.findByProject(TENANT, PROJECT).get(0).id(), 10)).isEmpty();
    }

    @Test
    void claim_advancesClaimedToRunning() {
        long routineId = routineRepo.insert(TENANT, PROJECT, "DATA_QUALITY", true, "0 0 * * * *", null, 120, 1L);
        scheduler.armTick();
        long runId = runRepo.findByRoutine(routineId, 10).get(0).id();
        assertThat(runRepo.findById(runId).orElseThrow().state()).isEqualTo(PatrolRunStates.CLAIMED);

        scheduler.claimTick();
        // claim 后事务内 CAS→RUNNING 已提交（异步 executeRun 随后推进终态）；断言已离开 CLAIMED
        assertThat(runRepo.findById(runId).orElseThrow().state()).isNotEqualTo(PatrolRunStates.CLAIMED);
    }
}
