package com.dataweave.master.application.incident;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

import javax.sql.DataSource;

import com.dataweave.master.domain.Uuid7;
import com.dataweave.master.domain.incident.Incident;
import com.dataweave.master.domain.incident.IncidentBriefing;
import com.dataweave.master.domain.incident.IncidentMessage;
import com.dataweave.master.domain.incident.IncidentStates;
import com.dataweave.master.domain.incident.MessageKinds;
import com.dataweave.master.infrastructure.incident.IncidentBriefingRepository;
import com.dataweave.master.infrastructure.incident.IncidentMessageRepository;
import com.dataweave.master.infrastructure.incident.IncidentRepository;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.SingleConnectionDataSource;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * 067 Phase 2 地基测试：开单唯一约束单赢/归并、CAS 状态推进、消息 seq 单调、briefing upsert。
 * 隔离 H2 库（对齐 SlotManagerDistributedIT 模式），不依赖 @SpringBootTest，避免上下文污染（记忆：H2 共享内存库测试串台）。
 */
class IncidentRepositoryIT {

    private DataSource ds;
    private JdbcTemplate jdbc;
    private IncidentRepository incidentRepo;
    private IncidentMessageRepository messageRepo;
    private IncidentBriefingRepository briefingRepo;

    @BeforeEach
    void setUp() {
        ds = new SingleConnectionDataSource(
                "jdbc:h2:mem:incident_repo_it;DB_CLOSE_DELAY=-1;MODE=PostgreSQL", true);
        jdbc = new JdbcTemplate(ds);
        jdbc.execute("""
                CREATE TABLE incident (
                    id UUID PRIMARY KEY,
                    tenant_id BIGINT NOT NULL,
                    project_id BIGINT NOT NULL,
                    task_def_id BIGINT NOT NULL,
                    task_def_name VARCHAR(255),
                    first_instance_id UUID NOT NULL,
                    latest_instance_id UUID NOT NULL,
                    instance_count INTEGER NOT NULL DEFAULT 1,
                    trigger_source VARCHAR(16),
                    classification VARCHAR(24),
                    confidence VARCHAR(8),
                    state VARCHAR(24) NOT NULL,
                    open_key BIGINT,
                    auto_action_count INTEGER NOT NULL DEFAULT 0,
                    summary VARCHAR(512),
                    suggestion VARCHAR(2000),
                    close_kind VARCHAR(16),
                    opened_at TIMESTAMP NOT NULL,
                    closed_at TIMESTAMP,
                    version INTEGER NOT NULL DEFAULT 0,
                    created_at TIMESTAMP NOT NULL,
                    updated_at TIMESTAMP NOT NULL,
                    CONSTRAINT uk_incident_open UNIQUE (tenant_id, open_key)
                )
                """);
        jdbc.execute("""
                CREATE TABLE incident_instance (
                    incident_id UUID NOT NULL,
                    instance_id UUID NOT NULL,
                    created_at TIMESTAMP NOT NULL,
                    CONSTRAINT pk_incident_instance PRIMARY KEY (incident_id, instance_id)
                )
                """);
        jdbc.execute("""
                CREATE TABLE incident_message (
                    id UUID PRIMARY KEY,
                    incident_id UUID NOT NULL,
                    seq BIGINT NOT NULL,
                    kind VARCHAR(16) NOT NULL,
                    content VARCHAR(4000),
                    payload_json VARCHAR(4000),
                    actor VARCHAR(64),
                    created_at TIMESTAMP NOT NULL,
                    CONSTRAINT uk_incident_message_seq UNIQUE (incident_id, seq)
                )
                """);
        jdbc.execute("""
                CREATE TABLE incident_briefing (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id BIGINT NOT NULL,
                    project_id BIGINT NOT NULL,
                    summary_line VARCHAR(512),
                    report_md VARCHAR(4000),
                    stats_json VARCHAR(512),
                    generated_at TIMESTAMP NOT NULL,
                    CONSTRAINT uk_incident_briefing_project UNIQUE (tenant_id, project_id)
                )
                """);
        incidentRepo = new IncidentRepository(jdbc);
        messageRepo = new IncidentMessageRepository(jdbc);
        briefingRepo = new IncidentBriefingRepository(jdbc);
    }

    @AfterEach
    void tearDown() {
        jdbc.execute("DROP ALL OBJECTS");
        ((SingleConnectionDataSource) ds).destroy();
    }

    @Test
    void tryOpen_secondCallForSameTaskConflictsAndReturnsEmpty() {
        long tenantId = 1L, projectId = 1L, taskDefId = 100L;
        UUID inst1 = Uuid7.generate();
        UUID inst2 = Uuid7.generate();

        Optional<Incident> first = incidentRepo.tryOpen(tenantId, projectId, taskDefId, "demo-task", inst1, "CRON");
        assertThat(first).isPresent();
        assertThat(first.get().state()).isEqualTo(IncidentStates.OPEN);
        assertThat(first.get().openKey()).isEqualTo(taskDefId);

        Optional<Incident> second = incidentRepo.tryOpen(tenantId, projectId, taskDefId, "demo-task", inst2, "CRON");
        assertThat(second).isEmpty();

        // 唯一约束单赢：同任务仍只有一条未收口事故
        assertThat(incidentRepo.findAllOpen(tenantId)).hasSize(1);
    }

    @Test
    void mergeInstance_incrementsCountAndUpdatesLatest() {
        long tenantId = 1L, taskDefId = 200L;
        UUID inst1 = Uuid7.generate();
        UUID inst2 = Uuid7.generate();
        Incident opened = incidentRepo.tryOpen(tenantId, 1L, taskDefId, "t", inst1, "MANUAL").orElseThrow();

        int rows = incidentRepo.mergeInstance(tenantId, taskDefId, inst2);
        assertThat(rows).isEqualTo(1);

        Incident merged = incidentRepo.findById(opened.id()).orElseThrow();
        assertThat(merged.instanceCount()).isEqualTo(2);
        assertThat(merged.latestInstanceId()).isEqualTo(inst2);
    }

    @Test
    void casState_onlySucceedsFromExpectedState() {
        UUID inst = Uuid7.generate();
        Incident opened = incidentRepo.tryOpen(1L, 1L, 300L, "t", inst, "CRON").orElseThrow();

        boolean wrongFrom = incidentRepo.casState(opened.id(), IncidentStates.ACTING, IncidentStates.RESOLVED);
        assertThat(wrongFrom).isFalse();

        boolean rightFrom = incidentRepo.casState(opened.id(), IncidentStates.OPEN, IncidentStates.ANALYZING);
        assertThat(rightFrom).isTrue();
        assertThat(incidentRepo.findById(opened.id()).orElseThrow().state()).isEqualTo(IncidentStates.ANALYZING);
    }

    @Test
    void casClose_releasesOpenKeyAndAllowsReopen() {
        long tenantId = 1L, taskDefId = 400L;
        UUID inst = Uuid7.generate();
        Incident opened = incidentRepo.tryOpen(tenantId, 1L, taskDefId, "t", inst, "CRON").orElseThrow();

        boolean closed = incidentRepo.casClose(opened.id(), "AUTO");
        assertThat(closed).isTrue();

        Incident after = incidentRepo.findById(opened.id()).orElseThrow();
        assertThat(after.state()).isEqualTo(IncidentStates.RESOLVED);
        assertThat(after.openKey()).isNull();
        assertThat(after.closedAt()).isNotNull();

        // open_key 释放后同任务可重新开单（NULL 不参与唯一冲突）
        Optional<Incident> reopened = incidentRepo.tryOpen(tenantId, 1L, taskDefId, "t", Uuid7.generate(), "CRON");
        assertThat(reopened).isPresent();
    }

    @Test
    void incrementAutoAction_onlyIncrements() {
        UUID inst = Uuid7.generate();
        Incident opened = incidentRepo.tryOpen(1L, 1L, 500L, "t", inst, "CRON").orElseThrow();
        incidentRepo.incrementAutoAction(opened.id());
        incidentRepo.incrementAutoAction(opened.id());
        assertThat(incidentRepo.findById(opened.id()).orElseThrow().autoActionCount()).isEqualTo(2);
    }

    @Test
    void messageSeq_isMonotonicPerIncident() {
        UUID incidentId = Uuid7.generate();
        // 独立测试消息序号，无需先建 incident 行（消息仓储不做 FK 约束校验）
        IncidentMessage m1 = messageRepo.append(incidentId, MessageKinds.SYSTEM, "opened", null, "system");
        IncidentMessage m2 = messageRepo.append(incidentId, MessageKinds.AGENT_STEP, "reading logs", null, "ops-agent");
        IncidentMessage m3 = messageRepo.append(incidentId, MessageKinds.AGENT_SAY, "diagnosis done", null, "ops-agent");

        assertThat(m1.seq()).isEqualTo(1L);
        assertThat(m2.seq()).isEqualTo(2L);
        assertThat(m3.seq()).isEqualTo(3L);

        List<IncidentMessage> after1 = messageRepo.findAfter(incidentId, 1L, 10);
        assertThat(after1).hasSize(2);
        assertThat(after1.get(0).seq()).isEqualTo(2L);
    }

    @Test
    void briefing_upsertKeepsSingleRowPerProject() {
        briefingRepo.upsert(1L, 1L, "first summary", "# report v1", "{}");
        briefingRepo.upsert(1L, 1L, "second summary", "# report v2", "{}");

        Optional<IncidentBriefing> found = briefingRepo.findByProject(1L, 1L);
        assertThat(found).isPresent();
        assertThat(found.get().summaryLine()).isEqualTo("second summary");

        Integer count = jdbc.queryForObject(
                "SELECT COUNT(*) FROM incident_briefing WHERE tenant_id=1 AND project_id=1", Integer.class);
        assertThat(count).isEqualTo(1);
    }
}
