package com.dataweave.master.application;

import com.dataweave.master.domain.EventBus;
import com.dataweave.master.domain.InstanceStates;
import com.dataweave.master.domain.WorkerNodeRepository;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import javax.sql.DataSource;
import java.time.LocalDateTime;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.mock;

/**
 * 060（T010）LeaseReaper test：infra 回收分类与计数（FR-007/008/012/019）。
 *
 * <p>真 H2 + 真 InstanceStateMachine/NodeHealthService（CAS 实际执行），验证：
 * <ul>
 *   <li>WORKER_LOST 回收：state→WAITING、business_attempt 不变、infra_count+1、清 worker_node_code、节点熔断+1。</li>
 *   <li>WORKER_RESTART 回收：同上但不计节点熔断（正常重启，D4）。</li>
 *   <li>infra 重派超上限 → SUSPENDED（毒任务保护，不判死 FR-012）。</li>
 * </ul>
 */
class LeaseReaperTest {

    private DataSource ds;
    private JdbcTemplate jdbc;
    private LeaseReaper reaper;
    private UUID instanceId;
    private static final int INFRA_MAX = 2;

    @BeforeEach
    void setUp() {
        ds = new DriverManagerDataSource("jdbc:h2:mem:leasereaper_it;MODE=PostgreSQL;DB_CLOSE_DELAY=-1", "sa", "");
        jdbc = new JdbcTemplate(ds);
        try { jdbc.execute("DROP ALL OBJECTS"); } catch (Exception ignored) {}
        jdbc.execute("CREATE TABLE task_instance (id UUID PRIMARY KEY, state VARCHAR(32), worker_node_code VARCHAR(64), "
                + "attempt INTEGER DEFAULT 0, workflow_instance_id UUID, lease_expire_at TIMESTAMP, "
                + "infra_redispatch_count INTEGER DEFAULT 0, business_attempt INTEGER DEFAULT 0, "
                + "failure_reason VARCHAR(64), started_at TIMESTAMP, finished_at TIMESTAMP, "
                + "updated_at TIMESTAMP, deleted SMALLINT DEFAULT 0)");
        jdbc.execute("CREATE TABLE worker_nodes (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "node_code VARCHAR(64), status VARCHAR(32), incarnation BIGINT, last_heartbeat TIMESTAMP, "
                + "incarnation_since TIMESTAMP, consecutive_infra_failures INTEGER DEFAULT 0, "
                + "quarantined_until TIMESTAMP, updated_at TIMESTAMP, deleted SMALLINT DEFAULT 0)");
        jdbc.execute("CREATE TABLE task_def (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(256))");

        InstanceStateMachine stateMachine = new InstanceStateMachine(jdbc, mock(EventBus.class),
                mock(ApplicationEventPublisher.class));
        NodeHealthService nodeHealthService = new NodeHealthService(jdbc, 3, 30_000L);
        reaper = new LeaseReaper(jdbc, stateMachine, nodeHealthService, mock(WorkerNodeRepository.class),
                mock(EventBus.class), mock(SchedulerMetrics.class), mock(ApplicationEventPublisher.class),
                mock(WorkflowStateService.class), INFRA_MAX);
        instanceId = UUID.randomUUID();
    }

    @AfterEach
    void tearDown() {
        if (ds instanceof AutoCloseable c) {
            try { c.close(); } catch (Exception ignored) {}
        }
    }

    /** 种一个 DISPATCHED 实例到指定节点（租约已过期），返回实例 id。 */
    private void seedInstance(String nodeCode, int infraCount) {
        jdbc.update("INSERT INTO task_instance (id, state, worker_node_code, attempt, lease_expire_at, "
                        + "infra_redispatch_count, business_attempt, started_at, updated_at, deleted) "
                        + "VALUES (?,?,?,?,?,?,?,?,?,0)",
                instanceId, InstanceStates.DISPATCHED, nodeCode, 1,
                LocalDateTime.now().minusSeconds(60), infraCount, 5 /*business_attempt 不应被 infra 回收改动*/,
                LocalDateTime.now().minusSeconds(120), LocalDateTime.now());
    }

    private void seedNode(String nodeCode, String status) {
        jdbc.update("INSERT INTO worker_nodes (node_code, status, consecutive_infra_failures, deleted) VALUES (?,?,0,0)",
                nodeCode, status);
    }

    private String state() {
        return jdbc.queryForObject("SELECT state FROM task_instance WHERE id=?", String.class, instanceId);
    }

    private Integer infraCount() {
        return jdbc.queryForObject("SELECT infra_redispatch_count FROM task_instance WHERE id=?", Integer.class, instanceId);
    }

    private Integer businessAttempt() {
        Integer b = jdbc.queryForObject("SELECT business_attempt FROM task_instance WHERE id=?", Integer.class, instanceId);
        return b != null ? b : 0;
    }

    private String workerNodeCode() {
        return jdbc.queryForObject("SELECT worker_node_code FROM task_instance WHERE id=?", String.class, instanceId);
    }

    private int nodeFailures(String nodeCode) {
        Integer f = jdbc.queryForObject(
                "SELECT consecutive_infra_failures FROM worker_nodes WHERE node_code=?", Integer.class, nodeCode);
        return f != null ? f : 0;
    }

    @Test
    void workerLost_reclaim_doesNotBurnBusiness_incrementsInfra_countsQuarantine() {
        seedNode("dead-node", "OFFLINE");
        seedInstance("dead-node", 0);  // infra_count=0, business_attempt=5

        reaper.reap();

        assertThat(state()).isEqualTo(InstanceStates.WAITING);       // 回 WAITING（非终态，FR-008）
        assertThat(businessAttempt()).isEqualTo(5);                  // business_attempt 不变（FR-008）
        assertThat(infraCount()).isEqualTo(1);                       // infra_count+1
        assertThat(workerNodeCode()).isNull();                       // 清 worker（转移，FR-010）
        assertThat(nodeFailures("dead-node")).isEqualTo(1);          // WORKER_LOST 计熔断（FR-003）
    }

    @Test
    void workerRestart_reclaim_doesNotCountQuarantine() {
        seedNode("restarted-node", "ONLINE");
        seedInstance("restarted-node", 0);

        reaper.reap();

        assertThat(state()).isEqualTo(InstanceStates.WAITING);
        assertThat(infraCount()).isEqualTo(1);
        // WORKER_RESTART（正常重启）不计熔断——由稳定窗处置（D4），避免滚动重启节点被误隔离
        assertThat(nodeFailures("restarted-node")).isEqualTo(0);
    }

    @Test
    void infraRedispatchOverMax_suspendsNotFailed() {
        seedNode("dead-node", "OFFLINE");
        seedInstance("dead-node", INFRA_MAX);  // 已达上限，再回收 → 超限

        reaper.reap();

        assertThat(state()).isEqualTo(InstanceStates.SUSPENDED);  // 毒任务保护挂起，不判死（FR-012）
        assertThat(infraCount()).isEqualTo(INFRA_MAX + 1);        // 仍 +1
        assertThat(businessAttempt()).isEqualTo(5);               // 仍不烧 business_attempt
    }
}
