package com.dataweave.master.application;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import javax.sql.DataSource;
import java.time.LocalDateTime;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * 060（T009）NodeHealthService test：熔断计数原子/单调更新（FR-003/006）。
 *
 * <p>用真 H2（非 mock）验证 SQL 原子性：{@code consecutive_infra_failures=x+1} 与 {@code quarantined_until=GREATEST}
 * 在并发下不丢更新、只增不减，结果与串行等价。多线程经 DriverManagerDataSource 取独立连接打到同一内存库。
 */
class NodeHealthServiceTest {

    private DataSource ds;
    private JdbcTemplate jdbc;
    private NodeHealthService health;

    @BeforeEach
    void setUp() {
        ds = new DriverManagerDataSource("jdbc:h2:mem:nodehealth_it;MODE=PostgreSQL;DB_CLOSE_DELAY=-1", "sa", "");
        jdbc = new JdbcTemplate(ds);
        try { jdbc.execute("DROP ALL OBJECTS"); } catch (Exception ignored) {}
        jdbc.execute("CREATE TABLE worker_nodes (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, node_code VARCHAR(64), "
                + "consecutive_infra_failures INTEGER DEFAULT 0, quarantined_until TIMESTAMP, incarnation_since TIMESTAMP, "
                + "updated_at TIMESTAMP, deleted SMALLINT DEFAULT 0)");
        jdbc.update("INSERT INTO worker_nodes (node_code) VALUES (?)", "node-1");
        // threshold=3, backoff=30s
        health = new NodeHealthService(jdbc, 3, 30_000L);
    }

    @AfterEach
    void tearDown() {
        if (ds instanceof AutoCloseable c) {
            try { c.close(); } catch (Exception ignored) {}
        }
    }

    @Test
    void recordInfraFailure_incrementsAndQuarantinesAtThreshold() {
        health.recordInfraFailure("node-1");  // 1 < 3
        assertThat(failures()).isEqualTo(1);
        assertThat(quarantinedUntil()).isNull();

        health.recordInfraFailure("node-1");  // 2 < 3
        health.recordInfraFailure("node-1");  // 3 >= 3 → 隔离
        assertThat(failures()).isEqualTo(3);
        assertThat(quarantinedUntil()).isNotNull();
        assertThat(quarantinedUntil()).isAfterOrEqualTo(LocalDateTime.now());  // 未来时刻
    }

    @Test
    void quarantinedUntil_isMonotonicGreatest() {
        // 先隔离（落一个 backoff 时刻）
        for (int i = 0; i < 3; i++) health.recordInfraFailure("node-1");
        LocalDateTime firstQuarantine = quarantinedUntil();
        // 再次故障：GREATEST(旧, now+backoff) —— 新 backoff 时刻应 >= 旧（不回退）
        health.recordInfraFailure("node-1");
        assertThat(quarantinedUntil()).isAfterOrEqualTo(firstQuarantine);
    }

    @Test
    void clearOnSuccess_resets() {
        for (int i = 0; i < 3; i++) health.recordInfraFailure("node-1");
        assertThat(quarantinedUntil()).isNotNull();

        health.clearOnSuccess("node-1");  // 成功执行一次 → 复位（FR-004）
        assertThat(failures()).isEqualTo(0);
        assertThat(quarantinedUntil()).isNull();
    }

    /**
     * 并发无丢失更新（FR-006）：8 线程各 20 次 recordInfraFailure，最终计数必须 == 160（不丢），
     * quarantined_until 落定（>>阈值）。证明原子自增在对等 master 并发下结果与串行等价。
     */
    @Test
    void concurrentRecordInfraFailure_noLostUpdates() throws Exception {
        int threads = 8;
        int perThread = 20;
        int total = threads * perThread;
        ExecutorService pool = Executors.newFixedThreadPool(threads);
        CountDownLatch start = new CountDownLatch(1);
        CountDownLatch done = new CountDownLatch(threads);
        AtomicInteger errors = new AtomicInteger();
        for (int t = 0; t < threads; t++) {
            pool.submit(() -> {
                try {
                    start.await();
                    for (int i = 0; i < perThread; i++) {
                        health.recordInfraFailure("node-1");
                    }
                } catch (Exception e) {
                    errors.incrementAndGet();
                } finally {
                    done.countDown();
                }
            });
        }
        start.countDown();
        assertThat(done.await(30, TimeUnit.SECONDS)).isTrue();
        pool.shutdownNow();
        assertThat(errors.get()).isZero();

        assertThat(failures()).isEqualTo(total);  // 无丢失更新
        assertThat(quarantinedUntil()).isNotNull();  // >>阈值，已隔离
    }

    private int failures() {
        Integer f = jdbc.queryForObject(
                "SELECT consecutive_infra_failures FROM worker_nodes WHERE node_code=?", Integer.class, "node-1");
        return f != null ? f : 0;
    }

    private LocalDateTime quarantinedUntil() {
        return jdbc.queryForObject(
                "SELECT quarantined_until FROM worker_nodes WHERE node_code=?", LocalDateTime.class, "node-1");
    }
}
