package com.dataweave.master.companion.application;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.function.Consumer;

import javax.sql.DataSource;

import com.dataweave.master.companion.domain.CompanionStates;
import com.dataweave.master.companion.domain.ReportSeverities;
import com.dataweave.master.companion.domain.ReportStatuses;
import com.dataweave.master.companion.infrastructure.JdbcPatrolReportRepository;
import com.dataweave.master.companion.infrastructure.JdbcPatrolRunRepository;
import com.dataweave.master.domain.EventBus;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.SingleConnectionDataSource;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * CompanionStateResolver 优先级矩阵单测（T010）：speak > think > alert > patrol > idle。
 * 单连 H2 内联 patrol_run/patrol_report/patrol_routine 表 + capturing EventBus（不发真事件，断言优先级与变更通知）。
 */
class CompanionStateResolverTest {

    private static final long TENANT = 1L;
    private static final long PROJECT = 1L;

    private DataSource ds;
    private JdbcTemplate jdbc;
    private JdbcPatrolReportRepository reportRepo;
    private JdbcPatrolRunRepository runRepo;
    private CompanionTurnRegistry registry;
    private List<String> published;
    private CompanionStateResolver resolver;

    @BeforeEach
    void setUp() {
        ds = new SingleConnectionDataSource(
                "jdbc:h2:mem:companion_state_it;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;" +
                "DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE", true);
        jdbc = new JdbcTemplate(ds);
        jdbc.execute("""
                CREATE TABLE patrol_routine (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id BIGINT NOT NULL, project_id BIGINT NOT NULL,
                    domain VARCHAR(32) NOT NULL, enabled SMALLINT NOT NULL DEFAULT 1,
                    cron_expression VARCHAR(64) NOT NULL, scope_json TEXT,
                    timeout_seconds INTEGER NOT NULL DEFAULT 120,
                    created_by BIGINT, updated_by BIGINT,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    deleted SMALLINT NOT NULL DEFAULT 0, version INTEGER NOT NULL DEFAULT 0)
                """);
        jdbc.execute("""
                CREATE TABLE patrol_run (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id BIGINT NOT NULL, project_id BIGINT NOT NULL,
                    routine_id BIGINT NOT NULL, trigger_type VARCHAR(16) NOT NULL,
                    scheduled_fire_time TIMESTAMP NOT NULL, state VARCHAR(16) NOT NULL DEFAULT 'CLAIMED',
                    started_at TIMESTAMP, finished_at TIMESTAMP, summary TEXT, error TEXT,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    version INTEGER NOT NULL DEFAULT 0)
                """);
        jdbc.execute("""
                CREATE TABLE patrol_report (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id BIGINT NOT NULL, project_id BIGINT NOT NULL,
                    run_id BIGINT, domain VARCHAR(32) NOT NULL, severity VARCHAR(16) NOT NULL,
                    title VARCHAR(255) NOT NULL, summary TEXT, detail_json TEXT,
                    aggregate_count INTEGER NOT NULL DEFAULT 1, status VARCHAR(16) NOT NULL DEFAULT 'UNREAD',
                    closed_by VARCHAR(128), closed_at TIMESTAMP,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)
                """);
        reportRepo = new JdbcPatrolReportRepository(jdbc);
        runRepo = new JdbcPatrolRunRepository(jdbc);
        registry = new CompanionTurnRegistry();
        published = new ArrayList<>();
        EventBus fakeBus = new EventBus() {
            @Override public void publish(String channel, String message) { published.add(channel + "|" + message); }
            @Override public Subscription subscribe(String channel, Consumer<String> handler) { return () -> {}; }
        };
        resolver = new CompanionStateResolver(reportRepo, runRepo, registry, new CompanionEventPublisher(fakeBus));
    }

    @AfterEach
    void tearDown() {
        jdbc.execute("DROP ALL OBJECTS");
        ((SingleConnectionDataSource) ds).destroy();
    }

    @Test
    void priorityMatrix_speakOverThinkOverAlertOverPatrolOverIdle() {
        // 空白 → idle
        assertThat(resolver.resolve(TENANT, PROJECT)).isEqualTo(CompanionStates.IDLE);

        // RUNNING run（无异常）→ patrol
        seedRunning();
        assertThat(resolver.resolve(TENANT, PROJECT)).isEqualTo(CompanionStates.PATROL);

        // 未关闭异常 → alert（alert > patrol）
        seedReport(ReportSeverities.DANGER, ReportStatuses.UNREAD);
        assertThat(resolver.resolve(TENANT, PROJECT)).isEqualTo(CompanionStates.ALERT);

        // think 轮次 → think（think > alert）
        registry.markThink(PROJECT);
        assertThat(resolver.resolve(TENANT, PROJECT)).isEqualTo(CompanionStates.THINK);

        // speak 轮次 → speak（speak > think）
        registry.markSpeak(PROJECT);
        assertThat(resolver.resolve(TENANT, PROJECT)).isEqualTo(CompanionStates.SPEAK);

        // 回落：清 speak/think（仍 alert + patrol）→ alert
        registry.clear(PROJECT);
        assertThat(resolver.resolve(TENANT, PROJECT)).isEqualTo(CompanionStates.ALERT);
    }

    @Test
    void closedAnomalyFallsBackToIdleWhenNoPatrol() {
        long report = seedReport(ReportSeverities.WARN, ReportStatuses.UNREAD);
        assertThat(resolver.resolve(TENANT, PROJECT)).isEqualTo(CompanionStates.ALERT);

        // 关闭全部异常 → idle（无 RUNNING run、无活跃 turn）
        jdbc.update("UPDATE patrol_report SET status = 'CLOSED', closed_at = ? WHERE id = ?", LocalDateTime.now(), report);
        assertThat(resolver.resolve(TENANT, PROJECT)).isEqualTo(CompanionStates.IDLE);
    }

    @Test
    void resolveAndNotify_publishesStateOnlyOnChange() {
        resolver.resolveAndNotify(TENANT, PROJECT);
        long afterFirst = published.size();
        assertThat(afterFirst).isEqualTo(1);
        assertThat(published.get(published.size() - 1)).contains("\"event\":\"state\"").contains("\"idle\"");

        // 无变化 → 不发
        resolver.resolveAndNotify(TENANT, PROJECT);
        assertThat(published.size()).isEqualTo(afterFirst);

        // 产生异常 → 发 state=alert
        seedReport(ReportSeverities.DANGER, ReportStatuses.UNREAD);
        resolver.resolveAndNotify(TENANT, PROJECT);
        assertThat(published.size()).isEqualTo(afterFirst + 1);
        assertThat(published.get(published.size() - 1)).contains("\"alert\"");
    }

    private void seedRunning() {
        jdbc.update("INSERT INTO patrol_run (tenant_id, project_id, routine_id, trigger_type, " +
                "scheduled_fire_time, state, started_at) VALUES (?,?,1,'SCHEDULED',?, 'RUNNING', ?)",
                TENANT, PROJECT, LocalDateTime.now(), LocalDateTime.now());
    }

    private long seedReport(String severity, String status) {
        return reportRepo.insert(TENANT, PROJECT, null, "TASK_FAILURE", severity,
                "异常标题", "摘要", "{}", 1);
    }
}
