package com.dataweave.master.companion.application;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.function.Consumer;

import javax.sql.DataSource;

import com.dataweave.master.application.ActionRequest;
import com.dataweave.master.application.GatedActionService;
import com.dataweave.master.application.GateResult;
import com.dataweave.master.companion.domain.ChatCallbacks;
import com.dataweave.master.companion.domain.ChatHandle;
import com.dataweave.master.companion.domain.CompanionBrain;
import com.dataweave.master.companion.domain.CompanionMessage;
import com.dataweave.master.companion.domain.CompanionRoles;
import com.dataweave.master.companion.domain.PatrolResult;
import com.dataweave.master.companion.domain.PatrolRoutine;
import com.dataweave.master.companion.infrastructure.JdbcCompanionMessageRepository;
import com.dataweave.master.companion.infrastructure.JdbcPatrolReportRepository;
import com.dataweave.master.companion.infrastructure.JdbcPatrolRunRepository;
import com.dataweave.master.domain.EventBus;
import com.dataweave.master.i18n.BizException;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.SingleConnectionDataSource;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * CompanionChatService 单测（T025）：流式落 AGENT + 打断 end{interrupted:true} + 锚定上下文注入 + brain 降级。
 * scripted {@link CompanionBrain}（覆盖 selector.forChat）+ stub gate + inline H2；无真 workhorse。
 */
class CompanionChatServiceTest {

    private static final long TENANT = 1L;
    private static final long PROJECT = 1L;

    private DataSource ds;
    private JdbcTemplate jdbc;
    private JdbcCompanionMessageRepository messageRepo;
    private JdbcPatrolReportRepository reportRepo;
    private List<String> published;
    private CompanionChatService service;

    /** scripted brain 配置（每测试设）；null 表示 brain 不可用。 */
    private CompanionBrain brain;
    private volatile String capturedContext;

    @BeforeEach
    void setUp() {
        ds = new SingleConnectionDataSource(
                "jdbc:h2:mem:companion_chat_svc;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;" +
                "DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE", true);
        jdbc = new JdbcTemplate(ds);
        jdbc.execute("""
                CREATE TABLE companion_message (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id BIGINT NOT NULL, project_id BIGINT NOT NULL,
                    report_id BIGINT, role VARCHAR(16) NOT NULL,
                    actor VARCHAR(64), actor_name VARCHAR(128), content TEXT,
                    brain_session_id VARCHAR(128),
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)
                """);
        jdbc.execute("""
                CREATE TABLE patrol_report (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id BIGINT NOT NULL, project_id BIGINT NOT NULL,
                    run_id BIGINT, domain VARCHAR(32) NOT NULL, severity VARCHAR(16) NOT NULL,
                    title VARCHAR(255) NOT NULL, summary TEXT, detail_json TEXT,
                    aggregate_count INTEGER NOT NULL DEFAULT 1, status VARCHAR(16) NOT NULL DEFAULT 'UNREAD',
                    closed_by VARCHAR(128), closed_at TIMESTAMP,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)
                """);
        jdbc.execute("""
                CREATE TABLE patrol_run (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id BIGINT NOT NULL, project_id BIGINT NOT NULL,
                    routine_id BIGINT NOT NULL, trigger_type VARCHAR(16) NOT NULL,
                    scheduled_fire_time TIMESTAMP NOT NULL, state VARCHAR(16) NOT NULL DEFAULT 'CLAIMED',
                    started_at TIMESTAMP, finished_at TIMESTAMP, summary TEXT, error TEXT,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    version INTEGER NOT NULL DEFAULT 0)
                """);
        messageRepo = new JdbcCompanionMessageRepository(jdbc);
        reportRepo = new JdbcPatrolReportRepository(jdbc);
        JdbcPatrolRunRepository runRepo = new JdbcPatrolRunRepository(jdbc);
        published = new ArrayList<>();
        EventBus fakeBus = new EventBus() {
            @Override public void publish(String channel, String message) { published.add(message); }
            @Override public Subscription subscribe(String channel, Consumer<String> handler) { return () -> {}; }
        };
        CompanionEventPublisher publisher = new CompanionEventPublisher(fakeBus);
        CompanionBrainSelector selector = new CompanionBrainSelector(null, null) {
            @Override public Optional<CompanionBrain> forChat() {
                return brain == null ? Optional.empty() : Optional.of(brain);
            }
            @Override public CompanionBrain forPatrol() { return brain; }
        };
        CompanionTurnRegistry turnRegistry = new CompanionTurnRegistry();
        CompanionStateResolver stateResolver = new CompanionStateResolver(reportRepo, runRepo, turnRegistry, publisher);
        // stub gate：不触真实 PolicyEngine/executor，cancel 仅验打断行为
        GatedActionService stubGate = new GatedActionService(null, null, null, null, 30) {
            @Override public GateResult submit(ActionRequest req, Locale locale) {
                return new GateResult(GateResult.Outcome.EXECUTED, null, "L0", "ok", null, false, null);
            }
        };
        service = new CompanionChatService(messageRepo, reportRepo, selector, publisher, turnRegistry,
                stateResolver, stubGate, 2);
    }

    @AfterEach
    void tearDown() {
        jdbc.execute("DROP ALL OBJECTS");
        ((SingleConnectionDataSource) ds).destroy();
    }

    @Test
    void chat_streamsAndPersistsAgentReply() {
        brain = streamingBrain(new String[]{"Hello ", "Vega"}, false, new AtomicBoolean());

        service.chat(TENANT, PROJECT, null, "你好", "admin", "管理员", Locale.ENGLISH);

        CompanionMessage agent = awaitAgent(null);
        assertThat(agent.role()).isEqualTo(CompanionRoles.AGENT);
        assertThat(agent.content()).isEqualTo("Hello Vega");
        assertThat(agent.brainSessionId()).isEqualTo("sess-test");
        // USER 回显 + AGENT 各一条 message 事件；2 条 delta；end 非打断
        assertThat(published.stream().filter(s -> s.contains("\"delta\""))).hasSize(2);
        assertThat(published.stream().filter(s -> s.contains("\"end\"") && s.contains("\"interrupted\":false"))).hasSize(1);
    }

    @Test
    void cancel_interruptsStream() {
        AtomicBoolean cancelFlag = new AtomicBoolean();
        brain = streamingBrain(new String[]{"a", "b", "c", "d", "e", "f", "g", "h"}, true, cancelFlag);

        service.chat(TENANT, PROJECT, null, "长任务", "admin", "管理员", Locale.ENGLISH);
        sleepQuiet(180);   // 等 respond 进入 send（已注册 handle，正在慢速吐 delta）
        boolean cancelled = service.cancel(TENANT, PROJECT, null, "admin", Locale.ENGLISH);

        assertThat(cancelled).isTrue();
        awaitAgent(null);
        assertThat(published.stream().filter(s -> s.contains("\"end\"") && s.contains("\"interrupted\":true")))
                .hasSize(1);
    }

    @Test
    void anchoredContext_injectsReport() {
        long reportId = reportRepo.insert(TENANT, PROJECT, null, "TASK_FAILURE", "DANGER",
                "ETL 链路失败", "三连失败", "{}", 3);
        brain = streamingBrain(new String[]{"建议重跑"}, false, new AtomicBoolean());

        service.chat(TENANT, PROJECT, reportId, "怎么处理", "admin", "管理员", Locale.ENGLISH);
        awaitAgent(reportId);

        assertThat(capturedContext).contains("ETL 链路失败").contains("TASK_FAILURE");
    }

    @Test
    void brainUnavailable_throws() {
        brain = null;   // 模拟 workhorse 不可用
        assertThatThrownBy(() -> service.chat(TENANT, PROJECT, null, "你好", "admin", "管理员", Locale.ENGLISH))
                .isInstanceOf(BizException.class)
                .hasMessageContaining("companion.brain_unavailable");
        // 不留 USER 消息（降级前未落库）
        assertThat(messageRepo.findByProject(TENANT, PROJECT, null, null, 10)).isEmpty();
    }

    @Test
    void sessionReuse_continuesSameBrainSession() {
        // 预置一条带 brain_session_id 的 AGENT 消息（模拟上一轮）
        messageRepo.insert(TENANT, PROJECT, null, CompanionRoles.AGENT, "companion-agent", "Vega",
                "上一轮回复", "sess-old");
        brain = streamingBrain(new String[]{"第二轮"}, false, new AtomicBoolean());

        service.chat(TENANT, PROJECT, null, "继续", "admin", "管理员", Locale.ENGLISH);
        CompanionMessage agent = awaitAgent(null);

        // M4：复用既有 session（sess-old）续聊，不新建；新 AGENT 消息带同一 brain_session_id
        assertThat(agent.brainSessionId()).isEqualTo("sess-old");
    }

    @Test
    void chat_busy_rejectsConcurrentTurn() throws Exception {
        AtomicBoolean cancelFlag = new AtomicBoolean();
        brain = streamingBrain(new String[]{"a", "b", "c"}, true, cancelFlag);   // slow：send 占据 handle
        service.chat(TENANT, PROJECT, null, "第一轮", "admin", "管理员", Locale.ENGLISH);
        sleepQuiet(120);   // 等 respond 注册 handle 进入慢速 send

        // MINOR①：同会话已有进行中轮次 → 拒绝 companion.chat_busy
        assertThatThrownBy(() -> service.chat(TENANT, PROJECT, null, "第二轮", "admin", "管理员", Locale.ENGLISH))
                .isInstanceOf(BizException.class)
                .hasMessageContaining("companion.chat_busy");
        cancelFlag.set(true);   // 释放第一轮
    }

    /** 等异步 respond 落 AGENT 消息（轮询，≤5s）。{@code sessionReportId} 指定会话（null=全局）。 */
    private CompanionMessage awaitAgent(Long sessionReportId) {
        long t0 = System.currentTimeMillis();
        while (System.currentTimeMillis() - t0 < 5_000) {
            List<CompanionMessage> agents = messageRepo.findByProject(TENANT, PROJECT, sessionReportId, null, 50).stream()
                    .filter(m -> CompanionRoles.AGENT.equals(m.role())).toList();
            if (!agents.isEmpty()) return agents.get(agents.size() - 1);
            sleepQuiet(50);
        }
        throw new IllegalStateException("AGENT 消息未在 5s 内出现 (session=" + sessionReportId + ")");
    }

    /** 构造一个 scripted brain：send 按 deltas 吐增量，slow 时每段 sleep 80ms 便于打断。
     *  覆写 resumeChat：复用既有 sessionId 续聊（M4 验证用）。 */
    private CompanionBrain streamingBrain(String[] deltas, boolean slow, AtomicBoolean cancelFlag) {
        return new CompanionBrain() {
            @Override public ChatHandle openChat(long projectId, String contextPrompt, ChatCallbacks cb) {
                capturedContext = contextPrompt;
                return scriptedHandle("sess-test", deltas, slow, cancelFlag, cb);
            }
            @Override public java.util.Optional<ChatHandle> resumeChat(String sessionId, ChatCallbacks cb) {
                return java.util.Optional.of(scriptedHandle(sessionId, deltas, slow, cancelFlag, cb));   // M4：乐观复用
            }
            @Override public PatrolResult runPatrol(PatrolRoutine r, String s, int t) { return null; }
            @Override public boolean healthy() { return true; }
            @Override public String name() { return "scripted"; }
        };
    }

    private ChatHandle scriptedHandle(String sessionId, String[] deltas, boolean slow,
                                      AtomicBoolean cancelFlag, ChatCallbacks cb) {
        return new ChatHandle() {
            @Override public String sessionId() { return sessionId; }
            @Override public String send(String userText) {
                StringBuilder full = new StringBuilder();
                boolean interrupted = false;
                for (String d : deltas) {
                    if (cancelFlag.get()) { interrupted = true; break; }
                    cb.onDelta(d);
                    full.append(d);
                    if (slow) sleepQuiet(80);
                }
                cb.onEnd(full.toString(), interrupted);
                return full.toString();
            }
            @Override public void cancel() { cancelFlag.set(true); }
        };
    }

    private static void sleepQuiet(long ms) {
        try { Thread.sleep(ms); } catch (InterruptedException e) { Thread.currentThread().interrupt(); }
    }
}
