package com.dataweave.master.application.readiness;

import org.springframework.jdbc.core.JdbcTemplate;

/**
 * 051 测试辅助：手动建表（dataweave-master 测试 classpath 不含 dataweave-api 的 schema.sql）。
 */
public final class ReadinessTestHelper {

    private ReadinessTestHelper() {}

    /** 创建就绪态测试所需的最小表集。 */
    public static void createMinimalSchema(JdbcTemplate jdbc) {
        jdbc.execute("""
                CREATE TABLE tenants (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    code VARCHAR(64) NOT NULL,
                    name VARCHAR(128) NOT NULL,
                    status VARCHAR(32) DEFAULT 'ACTIVE',
                    created_by BIGINT, updated_by BIGINT,
                    created_at TIMESTAMP, updated_at TIMESTAMP,
                    deleted SMALLINT DEFAULT 0, version INTEGER DEFAULT 0
                )""");
        jdbc.execute("""
                CREATE TABLE projects (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id BIGINT NOT NULL,
                    code VARCHAR(64) NOT NULL,
                    name VARCHAR(128) NOT NULL,
                    owner_id BIGINT, status VARCHAR(32) DEFAULT 'ACTIVE',
                    created_by BIGINT, updated_by BIGINT,
                    created_at TIMESTAMP, updated_at TIMESTAMP,
                    deleted SMALLINT DEFAULT 0, version INTEGER DEFAULT 0
                )""");
        jdbc.execute("""
                CREATE TABLE task_def (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id BIGINT NOT NULL, project_id BIGINT NOT NULL,
                    name VARCHAR(256) NOT NULL, type VARCHAR(32) NOT NULL,
                    content VARCHAR(4000), timeout_sec INTEGER,
                    datasource_id BIGINT, target_datasource_id BIGINT,
                    params_json VARCHAR(2000),
                    status VARCHAR(32) DEFAULT 'DRAFT',
                    current_version_no INTEGER DEFAULT 0,
                    created_by BIGINT, updated_by BIGINT,
                    created_at TIMESTAMP, updated_at TIMESTAMP,
                    deleted SMALLINT DEFAULT 0, version INTEGER DEFAULT 0
                )""");
        jdbc.execute("""
                CREATE TABLE workflow_def (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id BIGINT NOT NULL, project_id BIGINT NOT NULL,
                    name VARCHAR(256) NOT NULL,
                    schedule_type VARCHAR(32) DEFAULT 'MANUAL',
                    cron VARCHAR(128),
                    status VARCHAR(32) DEFAULT 'DRAFT',
                    current_version_no INTEGER DEFAULT 0,
                    created_by BIGINT, updated_by BIGINT,
                    created_at TIMESTAMP, updated_at TIMESTAMP,
                    deleted SMALLINT DEFAULT 0, version INTEGER DEFAULT 0
                )""");
        jdbc.execute("""
                CREATE TABLE workflow_instance (
                    id UUID PRIMARY KEY, tenant_id BIGINT NOT NULL, project_id BIGINT NOT NULL,
                    workflow_id BIGINT NOT NULL, workflow_version_no INTEGER,
                    env VARCHAR(8) DEFAULT 'PROD', trigger_type VARCHAR(32),
                    state VARCHAR(32) DEFAULT 'NOT_RUN', priority INTEGER DEFAULT 5,
                    workflow_def_name VARCHAR(256), cron_expression VARCHAR(128),
                    scheduled_fire_time TIMESTAMP, biz_date VARCHAR(32),
                    total_tasks INTEGER DEFAULT 0, completed_tasks INTEGER DEFAULT 0,
                    failed_tasks INTEGER DEFAULT 0,
                    started_at TIMESTAMP, finished_at TIMESTAMP,
                    created_by BIGINT, updated_by BIGINT,
                    created_at TIMESTAMP, updated_at TIMESTAMP,
                    deleted SMALLINT DEFAULT 0, version INTEGER DEFAULT 0
                )""");
        jdbc.execute("""
                CREATE TABLE workflow_node (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id BIGINT NOT NULL, project_id BIGINT NOT NULL,
                    workflow_id BIGINT NOT NULL, task_id BIGINT,
                    node_type VARCHAR(32) DEFAULT 'TASK',
                    node_key VARCHAR(64), name VARCHAR(256),
                    pos_x INTEGER, pos_y INTEGER,
                    created_by BIGINT, updated_by BIGINT,
                    created_at TIMESTAMP, updated_at TIMESTAMP,
                    deleted SMALLINT DEFAULT 0, version INTEGER DEFAULT 0
                )""");
        jdbc.execute("""
                CREATE TABLE workflow_edge (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id BIGINT NOT NULL, project_id BIGINT NOT NULL,
                    workflow_id BIGINT NOT NULL,
                    from_node_id BIGINT NOT NULL, to_node_id BIGINT NOT NULL,
                    strength VARCHAR(16) DEFAULT 'STRONG',
                    created_by BIGINT, updated_by BIGINT,
                    created_at TIMESTAMP, updated_at TIMESTAMP,
                    deleted SMALLINT DEFAULT 0, version INTEGER DEFAULT 0
                )""");
        jdbc.execute("""
                CREATE TABLE workflow_dependency (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id BIGINT NOT NULL, project_id BIGINT NOT NULL,
                    workflow_id BIGINT NOT NULL, node_id BIGINT,
                    depend_workflow_id BIGINT NOT NULL, depend_node_id BIGINT,
                    date_offset VARCHAR(32) DEFAULT 'CURRENT_DAY',
                    dep_type VARCHAR(32) DEFAULT 'ALL_SUCCESS',
                    earliest_biz_date VARCHAR(32),
                    enabled SMALLINT DEFAULT 1,
                    created_by BIGINT, updated_by BIGINT,
                    created_at TIMESTAMP, updated_at TIMESTAMP,
                    deleted SMALLINT DEFAULT 0, version INTEGER DEFAULT 0
                )""");
        jdbc.execute("""
                CREATE TABLE task_instance (
                    id UUID PRIMARY KEY,
                    tenant_id BIGINT NOT NULL, project_id BIGINT NOT NULL,
                    workflow_instance_id UUID, workflow_node_id BIGINT,
                    task_id BIGINT, task_version_no INTEGER,
                    task_def_name VARCHAR(256), workflow_def_name VARCHAR(256),
                    cron_expression VARCHAR(128),
                    content_override TEXT, params_override TEXT, type_override VARCHAR(32),
                    run_mode VARCHAR(32) DEFAULT 'NORMAL',
                    backfill_run_id UUID, backfill_held SMALLINT DEFAULT 0,
                    env VARCHAR(8) DEFAULT 'PROD',
                    biz_date VARCHAR(32),
                    state VARCHAR(32) DEFAULT 'NOT_RUN',
                    attempt INTEGER DEFAULT 0,
                    worker_node_code VARCHAR(64),
                    lease_expire_at TIMESTAMP,
                    failure_reason VARCHAR(64),
                    started_at TIMESTAMP, finished_at TIMESTAMP,
                    log TEXT, exit_code INTEGER, error_message VARCHAR(2000),
                    created_by BIGINT, updated_by BIGINT,
                    created_at TIMESTAMP, updated_at TIMESTAMP,
                    deleted SMALLINT DEFAULT 0,
                    locale VARCHAR(16),
                    version INTEGER DEFAULT 0,
                    unmet_deps INTEGER NOT NULL DEFAULT 0
                )""");
    }

    /** 创建 readiness_signal 表（Maintainer 测试用）。 */
    public static void createReadinessSignalTable(JdbcTemplate jdbc) {
        jdbc.execute("""
                CREATE TABLE readiness_signal (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id BIGINT NOT NULL, project_id BIGINT NOT NULL,
                    kind VARCHAR(16) NOT NULL,
                    upstream_instance_id UUID NOT NULL,
                    workflow_id BIGINT, workflow_instance_id UUID,
                    workflow_node_id BIGINT, biz_date VARCHAR(32),
                    processed SMALLINT NOT NULL DEFAULT 0,
                    created_at TIMESTAMP, processed_at TIMESTAMP
                )""");
    }
}
