package com.dataweave.alert.infrastructure.jdbc;

import com.dataweave.alert.domain.AlertRule;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabase;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * 026 US3：AlertRuleJdbcRepository.findByEvalModeAndEnabled 跨租户查询（H2，独立库避免污染）。
 */
class AlertRuleCrossTenantQueryTest {

    private EmbeddedDatabase db;
    private AlertRuleJdbcRepository repo;

    @BeforeEach
    void setUp() {
        db = new EmbeddedDatabaseBuilder()
                .setType(EmbeddedDatabaseType.H2)
                .generateUniqueName(true) // 每个测试独立库名，避免共享内存库串台
                .build();
        JdbcTemplate jdbc = new JdbcTemplate(db);
        jdbc.execute("""
                CREATE TABLE alert_rule (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id BIGINT NOT NULL,
                    project_id BIGINT,
                    name VARCHAR(128) NOT NULL,
                    description VARCHAR(512),
                    enabled SMALLINT DEFAULT 1,
                    signal_source VARCHAR(32) NOT NULL,
                    eval_mode VARCHAR(16) NOT NULL,
                    eval_interval_sec INTEGER,
                    condition_json VARCHAR(2000),
                    severity VARCHAR(16) NOT NULL,
                    for_duration INTEGER DEFAULT 1,
                    dedup_key_template VARCHAR(256),
                    suppress_window_sec INTEGER DEFAULT 300,
                    auto_resolve SMALLINT DEFAULT 1,
                    labels_json VARCHAR(1000),
                    created_by BIGINT,
                    updated_by BIGINT,
                    created_at TIMESTAMP,
                    updated_at TIMESTAMP,
                    deleted SMALLINT DEFAULT 0,
                    version INTEGER DEFAULT 0
                )
                """);
        repo = new AlertRuleJdbcRepository(jdbc);
    }

    @AfterEach
    void tearDown() {
        db.shutdown();
    }

    private AlertRule rule(long tenantId, String evalMode, int enabled) {
        AlertRule r = new AlertRule();
        r.setTenantId(tenantId);
        r.setName("rule-" + tenantId);
        r.setEnabled(enabled);
        r.setSignalSource("METRIC");
        r.setEvalMode(evalMode);
        r.setEvalIntervalSec(30);
        r.setConditionJson("{\"metric_key\":\"m\",\"comparator\":\"GT\",\"threshold\":1}");
        r.setSeverity("HIGH");
        r.setForDuration(1);
        r.setSuppressWindowSec(300);
        r.setAutoResolve(1);
        return r;
    }

    @Test
    void finds_enabled_poll_rules_across_all_tenants() {
        repo.save(rule(100L, "POLL", 1));   // 命中
        repo.save(rule(200L, "POLL", 1));   // 命中（不同租户）
        repo.save(rule(100L, "POLL", 0));   // 排除：disabled
        repo.save(rule(100L, "EVENT", 1));  // 排除：非 POLL

        List<AlertRule> rules = repo.findByEvalModeAndEnabled("POLL", 1);

        assertThat(rules).hasSize(2);
        assertThat(rules).extracting(AlertRule::getTenantId)
                .containsExactlyInAnyOrder(100L, 200L);
    }

    @Test
    void tenant_scoped_query_still_isolates() {
        repo.save(rule(100L, "POLL", 1));
        repo.save(rule(200L, "POLL", 1));

        List<AlertRule> onlyT100 = repo.findByTenantIdAndEvalModeAndEnabled(100L, "POLL", 1);

        assertThat(onlyT100).hasSize(1);
        assertThat(onlyT100.get(0).getTenantId()).isEqualTo(100L);
    }
}
