-- DataWeave 企业级 schema。兼容 PostgreSQL / H2 的通用 DDL。
-- 设计真相源：openspec/changes/agent-native-cockpit/design-data-model.md
-- 公共审计列：tenant_id, project_id, created_by, updated_by, created_at, updated_at, deleted, version
--   · 全局表（tenants/permissions/datasource_types/worker_nodes）无 tenant_id/project_id
--   · 租户级表有 tenant_id 无 project_id；项目级表两者都有
-- 自增：GENERATED BY DEFAULT AS IDENTITY；JSON 统一存 VARCHAR（保 H2 兼容）；枚举用 VARCHAR(32)。

-- ===== DROP（逆依赖序）=====
DROP TABLE IF EXISTS backfill_run;
DROP TABLE IF EXISTS agent_chat_file;
DROP TABLE IF EXISTS agent_chat_message;
DROP TABLE IF EXISTS agent_chat_session;
DROP TABLE IF EXISTS agent_action;
DROP TABLE IF EXISTS agent_step;
DROP TABLE IF EXISTS agent_run;
DROP TABLE IF EXISTS agent_session;
DROP TABLE IF EXISTS policy_rules;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS audit_log;
DROP TABLE IF EXISTS finding;
DROP TABLE IF EXISTS task_diagnosis;
DROP TABLE IF EXISTS alert_rules;
DROP TABLE IF EXISTS metric_lineage;
DROP TABLE IF EXISTS metric_dimension;
DROP TABLE IF EXISTS derived_metrics;
DROP TABLE IF EXISTS atomic_metrics;
DROP TABLE IF EXISTS dimensions;
DROP TABLE IF EXISTS sla_baseline;
DROP TABLE IF EXISTS cron_fire;
DROP TABLE IF EXISTS workflow_node_freeze;
DROP TABLE IF EXISTS workflow_dependency;
DROP TABLE IF EXISTS task_instance;
DROP TABLE IF EXISTS workflow_instance;
DROP TABLE IF EXISTS workflow_edge;
DROP TABLE IF EXISTS workflow_node;
DROP TABLE IF EXISTS workflow_def_version;
DROP TABLE IF EXISTS workflow_def;
DROP TABLE IF EXISTS task_def_version;
DROP TABLE IF EXISTS task_def;
DROP TABLE IF EXISTS entity_tag;
DROP TABLE IF EXISTS tag;
DROP TABLE IF EXISTS catalog_node;
DROP TABLE IF EXISTS driver_jars;
DROP TABLE IF EXISTS datasources;
DROP TABLE IF EXISTS notification_channels;
DROP TABLE IF EXISTS project_member;
DROP TABLE IF EXISTS role_permission;
DROP TABLE IF EXISTS user_role;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS worker_nodes;
DROP TABLE IF EXISTS datasource_types;
DROP TABLE IF EXISTS permissions;
DROP TABLE IF EXISTS tenants;
-- 表级血缘（table-lineage）：与下方 CREATE 配对，保证 mode=always 在持久库（PG）重启幂等。
DROP TABLE IF EXISTS task_run_table_io;
DROP TABLE IF EXISTS task_table_io;
DROP TABLE IF EXISTS data_table;

-- ============================================================
-- 域 A · 租户与 RBAC
-- ============================================================

CREATE TABLE tenants (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(64) NOT NULL UNIQUE,
    name       VARCHAR(128) NOT NULL,
    status     VARCHAR(32) DEFAULT 'ACTIVE',
    created_by BIGINT,
    updated_by BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    deleted    SMALLINT DEFAULT 0,
    version    INTEGER DEFAULT 0
);

CREATE TABLE permissions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(128) NOT NULL UNIQUE,
    name        VARCHAR(128) NOT NULL,
    resource    VARCHAR(64),
    action      VARCHAR(64),
    description VARCHAR(256),
    created_by  BIGINT,
    updated_by  BIGINT,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP,
    deleted     SMALLINT DEFAULT 0,
    version     INTEGER DEFAULT 0
);

CREATE TABLE projects (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id  BIGINT NOT NULL,
    code       VARCHAR(64) NOT NULL,
    name       VARCHAR(128) NOT NULL,
    owner_id   BIGINT,
    status     VARCHAR(32) DEFAULT 'ACTIVE',
    created_by BIGINT,
    updated_by BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    deleted    SMALLINT DEFAULT 0,
    version    INTEGER DEFAULT 0
);

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT NOT NULL,
    username      VARCHAR(128) NOT NULL,
    password_hash VARCHAR(256),
    display_name  VARCHAR(128),
    email         VARCHAR(256),
    phone         VARCHAR(32),
    status        VARCHAR(32) DEFAULT 'ACTIVE',
    created_by    BIGINT,
    updated_by    BIGINT,
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP,
    deleted       SMALLINT DEFAULT 0,
    version       INTEGER DEFAULT 0
);

CREATE TABLE roles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT NOT NULL,
    code        VARCHAR(64) NOT NULL,
    name        VARCHAR(128) NOT NULL,
    description VARCHAR(256),
    created_by  BIGINT,
    updated_by  BIGINT,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP,
    deleted     SMALLINT DEFAULT 0,
    version     INTEGER DEFAULT 0
);

CREATE TABLE user_role (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id  BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    role_id    BIGINT NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    deleted    SMALLINT DEFAULT 0,
    version    INTEGER DEFAULT 0
);

CREATE TABLE role_permission (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT NOT NULL,
    role_id       BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    created_by    BIGINT,
    updated_by    BIGINT,
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP,
    deleted       SMALLINT DEFAULT 0,
    version       INTEGER DEFAULT 0
);

CREATE TABLE project_member (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id  BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    role_id    BIGINT NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    deleted    SMALLINT DEFAULT 0,
    version    INTEGER DEFAULT 0
);

-- ============================================================
-- 域 B · 数据源
-- ============================================================

CREATE TABLE datasource_types (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(64) NOT NULL UNIQUE,
    name          VARCHAR(128) NOT NULL,
    category      VARCHAR(32),
    driver        VARCHAR(256),
    default_port  INTEGER,
    created_by    BIGINT,
    updated_by    BIGINT,
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP,
    deleted       SMALLINT DEFAULT 0,
    version       INTEGER DEFAULT 0
);

-- 驱动 jar 资产（datasource-driver-isolation）：上传的 JDBC 驱动 jar，按 tenant+sha256 去重，
-- 可被多个 datasources 通过 driver_jar_id 引用，经隔离 URLClassLoader 加载覆盖内置默认驱动。
CREATE TABLE driver_jars (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT NOT NULL,
    type_code     VARCHAR(64) NOT NULL,
    driver_class  VARCHAR(256),
    original_name VARCHAR(256),
    sha256        VARCHAR(64) NOT NULL,
    storage_type  VARCHAR(16),
    storage_key   VARCHAR(512),
    size_bytes    BIGINT,
    status        VARCHAR(32) DEFAULT 'PENDING',
    created_by    BIGINT,
    updated_by    BIGINT,
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP,
    deleted       SMALLINT DEFAULT 0,
    version       INTEGER DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_driver_jars_tenant_sha ON driver_jars (tenant_id, sha256);
CREATE INDEX IF NOT EXISTS idx_driver_jars_type ON driver_jars (type_code);

CREATE TABLE datasources (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT NOT NULL,
    project_id    BIGINT NOT NULL,
    name          VARCHAR(128) NOT NULL,
    type_code     VARCHAR(64) NOT NULL,
    host          VARCHAR(256),
    port          INTEGER,
    database_name VARCHAR(128),
    jdbc_url      VARCHAR(512),
    username      VARCHAR(128),
    password_enc  VARCHAR(512),
    props_json    VARCHAR(2000),
    description   VARCHAR(500),
    status            VARCHAR(32) DEFAULT 'ACTIVE',
    connection_status VARCHAR(32) DEFAULT 'UNKNOWN',
    driver_jar_id     BIGINT,
    created_by    BIGINT,
    updated_by    BIGINT,
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP,
    deleted       SMALLINT DEFAULT 0,
    version       INTEGER DEFAULT 0
);

-- ============================================================
-- 域 C · 任务与任务流 DAG
-- ============================================================

CREATE TABLE task_def (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           BIGINT NOT NULL,
    project_id          BIGINT NOT NULL,
    name                VARCHAR(256) NOT NULL,
    type                VARCHAR(32) NOT NULL,
    content             VARCHAR(4000),
    datasource_id       BIGINT,
    target_datasource_id BIGINT,
    params_json         VARCHAR(2000),
    timeout_sec         INTEGER,
    retry_max           INTEGER DEFAULT 0,
    status              VARCHAR(32) DEFAULT 'DRAFT',
    current_version_no  INTEGER DEFAULT 0,   -- 最后发布版本号（0=未发布）
    has_draft_change    SMALLINT DEFAULT 1,  -- 有未发布改动
    priority            INTEGER DEFAULT 5,   -- 执行优先级（0=最高，9=最低）
    frozen              SMALLINT DEFAULT 0,  -- 冻结（1=冻结）：调度认领跳过、不生成新周期实例；在途实例不受影响（data-ops-center）
    description         VARCHAR(512),        -- 任务描述
    owner_id            BIGINT,              -- 任务负责人
    created_by          BIGINT,
    updated_by          BIGINT,
    created_at          TIMESTAMP,
    updated_at          TIMESTAMP,
    deleted             SMALLINT DEFAULT 0,
    version             INTEGER DEFAULT 0,
    catalog_node_id     BIGINT               -- 所属类目文件夹（NULL=未分类；见 catalog_node）
);

-- 任务定义已发布版本快照（不可变，可回滚）
CREATE TABLE task_def_version (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id            BIGINT NOT NULL,
    project_id           BIGINT NOT NULL,
    task_id              BIGINT NOT NULL,
    version_no           INTEGER NOT NULL,
    name                 VARCHAR(256),
    type                 VARCHAR(32),
    content              VARCHAR(4000),
    datasource_id        BIGINT,
    target_datasource_id BIGINT,
    params_json          VARCHAR(2000),
    timeout_sec          INTEGER,
    retry_max            INTEGER,
    priority             INTEGER,              -- 发布时优先级快照
    description          VARCHAR(512),         -- 发布时描述快照
    remark               VARCHAR(512),
    published_by         BIGINT,
    published_at         TIMESTAMP,
    created_at           TIMESTAMP
);

CREATE TABLE workflow_def (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT NOT NULL,
    project_id    BIGINT NOT NULL,
    name          VARCHAR(256) NOT NULL,
    description   VARCHAR(512),
    schedule_type VARCHAR(32) DEFAULT 'MANUAL',  -- MANUAL / CRON / DEPENDENCY
    cron          VARCHAR(128),
    schedule_start TIMESTAMP,                     -- 调度生效起（空=不限）
    schedule_end   TIMESTAMP,                     -- 调度生效止（空=不限）
    status        VARCHAR(32) DEFAULT 'DRAFT',
    current_version_no INTEGER DEFAULT 0,   -- 最后发布版本号（0=未发布）
    has_draft_change   SMALLINT DEFAULT 1,  -- 有未发布改动
    last_fire_time  TIMESTAMP,               -- 上次调度触发时间（防重复触发）
    next_trigger_time TIMESTAMP,             -- 下一次计划触发时间（单值持久化；扫描以 next_trigger_time≤now+lookahead 捞取；NULL=首轮回填）
    schedule_interval_ms BIGINT,             -- FIXED_RATE/FIXED_DELAY 周期（毫秒）；CRON 为空
    priority        INTEGER DEFAULT 5,       -- 工作流优先级（0=最高，9=最低）
    preemptible     SMALLINT DEFAULT 0,      -- 可被高优任务软抢占（默认否；典型用途补数类可重跑任务）
    timeout_sec     INTEGER,                 -- 工作流级超时（秒）
    created_by    BIGINT,
    updated_by    BIGINT,
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP,
    deleted       SMALLINT DEFAULT 0,
    version       INTEGER DEFAULT 0,
    catalog_node_id BIGINT                   -- 所属类目文件夹（NULL=未分类；见 catalog_node）
);

-- cron 扫描索引：按类型+状态+下次触发时间范围捞取（distributed-cron-trigger）
CREATE INDEX IF NOT EXISTS idx_workflow_def_scan ON workflow_def (deleted, schedule_type, status, next_trigger_time);

-- 任务流定义已发布版本快照：dag_snapshot_json 冻结整张 DAG（节点+边+各节点 task 版本号）
CREATE TABLE workflow_def_version (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id         BIGINT NOT NULL,
    project_id        BIGINT NOT NULL,
    workflow_id       BIGINT NOT NULL,
    version_no        INTEGER NOT NULL,
    name              VARCHAR(256),
    description       VARCHAR(512),
    schedule_type     VARCHAR(32),
    cron              VARCHAR(128),
    dag_snapshot_json VARCHAR(8000),
    remark            VARCHAR(512),
    published_by      BIGINT,
    published_at      TIMESTAMP,
    created_at        TIMESTAMP
);

CREATE TABLE workflow_node (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT NOT NULL,
    project_id  BIGINT NOT NULL,
    workflow_id BIGINT NOT NULL,
    task_id     BIGINT,                       -- TASK 节点必填；VIRTUAL（zero-load）节点为空
    node_type   VARCHAR(32) DEFAULT 'TASK',   -- TASK | VIRTUAL（虚拟起始/汇聚锚点）
    node_key    VARCHAR(64),
    name        VARCHAR(256),
    pos_x       INTEGER,
    pos_y       INTEGER,
    created_by  BIGINT,
    updated_by  BIGINT,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP,
    deleted     SMALLINT DEFAULT 0,
    version     INTEGER DEFAULT 0
);

CREATE TABLE workflow_edge (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id    BIGINT NOT NULL,
    project_id   BIGINT NOT NULL,
    workflow_id  BIGINT NOT NULL,
    from_node_id BIGINT NOT NULL,
    to_node_id   BIGINT NOT NULL,
    strength     VARCHAR(16) DEFAULT 'STRONG',  -- 依赖强度：STRONG(下游等上游 SUCCESS) | WEAK(上游到终态即放行)；可空≡STRONG（workflow-dependency-modes）
    created_by   BIGINT,
    updated_by   BIGINT,
    created_at   TIMESTAMP,
    updated_at   TIMESTAMP,
    deleted      SMALLINT DEFAULT 0,
    version      INTEGER DEFAULT 0
);

-- 节点级 DAG 冻结 overlay（ops-center-publish-boundary）：运维侧临时止血，键 (workflow_id, node_key, instance_id)。
-- instance_id 为空=定义级（此后每个 cron 物化实例都跳该节点）；非空=实例级（仅该实例该节点）。
-- overlay 不写入发布快照 dag_snapshot_json，调度物化时叠加；冻结节点及其传递下游（含弱依赖边）SKIPPED。
CREATE TABLE workflow_node_freeze (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id    BIGINT NOT NULL,
    project_id   BIGINT NOT NULL,
    workflow_id  BIGINT NOT NULL,
    node_key     VARCHAR(64) NOT NULL,
    instance_id  UUID,                          -- 空=定义级；非空=该工作流实例级
    frozen       SMALLINT DEFAULT 1,            -- 1=冻结（解冻时删行或置 0）
    created_by   BIGINT,
    updated_by   BIGINT,
    created_at   TIMESTAMP,
    updated_at   TIMESTAMP,
    deleted      SMALLINT DEFAULT 0,
    version      INTEGER DEFAULT 0
);
-- 物化叠加查询：按 (workflow_id, instance_id) 取该工作流定义级 + 该实例实例级冻结节点。
CREATE INDEX IF NOT EXISTS idx_node_freeze_lookup ON workflow_node_freeze (workflow_id, instance_id, deleted);

-- ============================================================
-- 域 C2 · 类目树与标签（任务/工作流的组织层）
-- ============================================================

-- 文件夹类目树：只存文件夹节点；任务/工作流经 catalog_node_id 回指挂入。
-- 邻接表 parent_id（父子关系，根节点为空）+ 物化路径 path（形如 /1/4/9/，含首尾 /），
-- 支撑子树 LIKE 前缀查询、面包屑拆串、防环判定。path 为后端派生字段（REST 不接受）。
CREATE TABLE catalog_node (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT NOT NULL,
    project_id  BIGINT NOT NULL,
    parent_id   BIGINT,                        -- 父文件夹（NULL=根）
    name        VARCHAR(256) NOT NULL,
    path        VARCHAR(2000) NOT NULL,        -- 物化路径 /id/.../id/（含首尾 /）
    sort_order  INTEGER,                       -- 同级排序（NULL 视为 0）
    created_by  BIGINT,
    updated_by  BIGINT,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP,
    deleted     SMALLINT DEFAULT 0,
    version     INTEGER DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_catalog_node_parent ON catalog_node (parent_id);
CREATE INDEX IF NOT EXISTS idx_catalog_node_path ON catalog_node (path);
CREATE INDEX IF NOT EXISTS idx_catalog_node_project ON catalog_node (project_id);
CREATE INDEX IF NOT EXISTS idx_task_def_catalog ON task_def (catalog_node_id);
CREATE INDEX IF NOT EXISTS idx_workflow_def_catalog ON workflow_def (catalog_node_id);

-- 标签：项目内多维横切元数据，name 项目内唯一。删除走硬删（级联清 entity_tag）。
CREATE TABLE tag (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT NOT NULL,
    project_id  BIGINT NOT NULL,
    name        VARCHAR(128) NOT NULL,
    color       VARCHAR(32),                   -- 原始色串（推荐 hex #RRGGBB），后端不解析
    created_by  BIGINT,
    updated_by  BIGINT,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_tag_project_name ON tag (project_id, name);

-- 标签-资产 多态多对多：entity_type ∈ {TASK, WORKFLOW}
CREATE TABLE entity_tag (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_id      BIGINT NOT NULL,
    entity_type VARCHAR(16) NOT NULL,          -- TASK | WORKFLOW
    entity_id   BIGINT NOT NULL,
    created_at  TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_entity_tag ON entity_tag (tag_id, entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_entity_tag_entity ON entity_tag (entity_type, entity_id);

CREATE TABLE workflow_instance (
    id           UUID PRIMARY KEY,              -- UUIDv7（时间有序，由应用层 Uuid7 生成）
    tenant_id    BIGINT NOT NULL,
    project_id   BIGINT NOT NULL,
    workflow_id  BIGINT NOT NULL,
    workflow_version_no INTEGER,           -- 本次运行所跑的已发布版本（规定性快照版本号，名副其实）
    env          VARCHAR(8) DEFAULT 'PROD',  -- 运行环境：PROD(cron/正式手动) | DEV(画布试跑)；逻辑隔离标签，可空（NULL≡PROD），不强制所有触发路径 set
    trigger_type VARCHAR(32),
    state        VARCHAR(32) DEFAULT 'NOT_RUN',
    priority     INTEGER DEFAULT 5,         -- 实例优先级（继承自 workflow_def，触发时可覆盖）
    workflow_def_name VARCHAR(256),         -- 快照：workflow_def.name（物化时写入，免查询 JOIN）
    cron_expression   VARCHAR(128),         -- 快照：workflow_def.cron（物化时写入，免查询 JOIN）
    biz_date     VARCHAR(32),
    total_tasks     INTEGER DEFAULT 0,       -- 总节点数
    completed_tasks INTEGER DEFAULT 0,       -- 已完成节点数
    failed_tasks    INTEGER DEFAULT 0,       -- 失败节点数
    started_at   TIMESTAMP,
    finished_at  TIMESTAMP,
    created_by   BIGINT,
    updated_by   BIGINT,
    created_at   TIMESTAMP,
    updated_at   TIMESTAMP,
    deleted      SMALLINT DEFAULT 0,
    version      INTEGER DEFAULT 0
);

CREATE TABLE task_instance (
    id                   UUID PRIMARY KEY,       -- UUIDv7（时间有序，由应用层 Uuid7 生成）
    tenant_id            BIGINT NOT NULL,
    project_id           BIGINT NOT NULL,
    workflow_instance_id UUID,
    workflow_node_id     BIGINT,
    task_id              BIGINT,                 -- 普通节点必填；VIRTUAL（zero-load）节点实例为空
    task_version_no      INTEGER,            -- 本次运行所跑的 task 已发布版本（NULL=试跑草稿）
    task_def_name        VARCHAR(256),        -- 快照：task_def.name（物化时写入，免查询 JOIN）
    workflow_def_name    VARCHAR(256),        -- 快照：workflow_def.name（物化时写入，免查询 JOIN）
    cron_expression      VARCHAR(128),        -- 快照：workflow_def.cron（物化时写入，免查询 JOIN）
    content_override     TEXT,                 -- TEST 试跑携带的编辑器临时内容（含未保存改动）；非空则覆盖 task_def 草稿，不写 task_def
    params_override      TEXT,                 -- TEST 试跑携带的编辑器临时调度参数 JSON；与 content_override 同源（占位符按编辑器解析）
    type_override        VARCHAR(32),          -- TEST 试跑携带的编辑器临时任务类型（SQL/SHELL/ECHO）；非空则覆盖 task_def.type 选执行器
    run_mode             VARCHAR(32) DEFAULT 'NORMAL',  -- NORMAL 正式 / TEST 试跑调试 / BACKFILL 补数据（data-ops-center）
    backfill_run_id      UUID,                 -- 所属补数据批次（run_mode=BACKFILL 时非空；指向 backfill_run.id）
    backfill_held        SMALLINT DEFAULT 0,   -- 补数据 bizDate 粒度节流旁路标志（backfill-parallelism-throttle）：1=被持有不可认领，由 BackfillPromoter 完成即晋升 1→0；与认领状态正交（实例仍 WAITING）
    env                  VARCHAR(8) DEFAULT 'PROD',  -- 运行环境：PROD(cron/正式手动) | DEV(画布试跑)；与 run_mode 正交，可空（NULL≡PROD）
    biz_date             VARCHAR(32),          -- 业务日期（注入任务执行环境，幂等钥匙之一）
    state                VARCHAR(32) DEFAULT 'NOT_RUN',  -- NOT_RUN/WAITING/DISPATCHED/RUNNING/SUCCESS/FAILED/STOPPED/PREEMPTED/PAUSED
    attempt              INTEGER DEFAULT 0,
    worker_node_code     VARCHAR(64),
    lease_expire_at      TIMESTAMP,            -- 下发后的租约到期时刻（心跳续约；过期 → WORKER_LOST 回收）
    failure_reason       VARCHAR(64),          -- 失败归因：WORKER_RESTART / WORKER_LOST / TIMEOUT / EXIT_NONZERO …
    started_at           TIMESTAMP,
    finished_at          TIMESTAMP,
    log                  TEXT,                  -- 执行日志（不截断）
    exit_code            INTEGER,              -- 进程退出码（0=成功）
    error_message        VARCHAR(2000),        -- 结构化错误摘要
    created_by           BIGINT,
    updated_by           BIGINT,
    created_at           TIMESTAMP,
    updated_at           TIMESTAMP,
    deleted              SMALLINT DEFAULT 0,
    locale               VARCHAR(16),          -- 触发者 locale（BCP-47 tag，如 en-US/zh-CN）；NULL=老数据/占位实例，消费端兜底 zh-CN
    version              INTEGER DEFAULT 0
);

-- 补数据批次（data-ops-center）：一次「按 任务/工作流 × 日期区间」补数操作的父记录。
-- 进度（success/failed/running）不落库，查询时按 backfill_run_id 聚合子 task_instance 状态得出（避免计数器一致性问题）。
CREATE TABLE backfill_run (
    id                 UUID PRIMARY KEY,        -- UUIDv7
    tenant_id          BIGINT NOT NULL,
    project_id         BIGINT NOT NULL,
    target_type        VARCHAR(16) NOT NULL,   -- task | workflow
    target_id          BIGINT NOT NULL,        -- task_def.id 或 workflow_def.id
    target_name        VARCHAR(256),           -- 冗余目标名（列表展示用）
    date_start         VARCHAR(32) NOT NULL,   -- 业务日期区间起（yyyy-MM-dd，含）
    date_end           VARCHAR(32) NOT NULL,   -- 业务日期区间止（yyyy-MM-dd，含）
    include_downstream SMALLINT DEFAULT 0,     -- 1=同 bizDate 内级联下游
    parallelism        INTEGER DEFAULT 1,      -- 跨 bizDate 并发提交上限
    state              VARCHAR(32) DEFAULT 'RUNNING',  -- RUNNING / SUCCESS / FAILED / PARTIAL（由子实例聚合推导）
    total              INTEGER DEFAULT 0,      -- 生成的子实例总数（创建时落库）
    created_by         BIGINT,
    created_at         TIMESTAMP,
    updated_at         TIMESTAMP,
    deleted            SMALLINT DEFAULT 0,
    version            INTEGER DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_task_instance_backfill ON task_instance (backfill_run_id, deleted);
-- 节流晋升索引（backfill-parallelism-throttle）：BackfillPromoter 按 (run, held) 重算活跃/待晋升 bizDate。
-- 普通复合索引（非 partial）以兼容 H2；持有集随晋升单调缩小，开销可忽略。
CREATE INDEX IF NOT EXISTS idx_task_instance_backfill_held ON task_instance (backfill_run_id, backfill_held);

-- 热认领索引：SchedulerKernel.selectRunnable 按 (state, run_mode, deleted) 过滤 + updated_at 排序捞 WAITING。
-- 无此索引则随 SUCCESS 历史行累积全表扫描，认领变慢、吞吐线性衰减（实测 6k 行即显著）。H2 兼容（非 partial）。
CREATE INDEX IF NOT EXISTS idx_task_instance_claim ON task_instance (state, run_mode, deleted, updated_at);

-- 跨周期依赖查询索引（workflow-dependency-modes）：按 (workflow_node_id, biz_date) 查上一周期 SUCCESS 实例判定跨周期就绪。
CREATE INDEX IF NOT EXISTS idx_task_instance_node_bizdate ON task_instance (workflow_node_id, biz_date, deleted);

-- 跨任务流依赖（DAG 间）：下游工作流/节点 依赖 上游工作流(+节点) + 业务日期偏移
CREATE TABLE workflow_dependency (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id          BIGINT NOT NULL,
    project_id         BIGINT NOT NULL,
    workflow_id        BIGINT NOT NULL,                 -- 下游（依赖方）
    node_id            BIGINT,                          -- 下游承载依赖的节点（空=工作流级依赖）
    depend_workflow_id BIGINT NOT NULL,                 -- 上游（被依赖）
    depend_node_id     BIGINT,                          -- 上游具体节点（空=整条上游流）
    date_offset        VARCHAR(32) DEFAULT 'CURRENT_DAY', -- CURRENT_DAY / LAST_DAY / ...
    dep_type           VARCHAR(32) DEFAULT 'ALL_SUCCESS', -- 上游需满足的条件
    earliest_biz_date  VARCHAR(32),                       -- 最早回溯 bizDate；biz_date<此值的首周期跳过跨周期检查（首周期豁免），空=不启用（workflow-dependency-modes）
    enabled            SMALLINT DEFAULT 1,
    created_by         BIGINT,
    updated_by         BIGINT,
    created_at         TIMESTAMP,
    updated_at         TIMESTAMP,
    deleted            SMALLINT DEFAULT 0,
    version            INTEGER DEFAULT 0
);

-- cron 触发防重护栏表：每个 (workflow_id, scheduled_fire_time) 仅允许一行。
-- 多 master 都扫 cron、都尝试 INSERT，撞复合唯一键即放弃 —— 谁插入成功这次触发归谁，零协调（design D4）。
CREATE TABLE cron_fire (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id         BIGINT NOT NULL,
    scheduled_fire_time TIMESTAMP NOT NULL,
    workflow_instance_id UUID,                 -- 触发产生的实例（便于回溯）
    fired_at            TIMESTAMP,
    created_at          TIMESTAMP,
    CONSTRAINT uq_cron_fire UNIQUE (workflow_id, scheduled_fire_time)
);

-- SLA 基线：按 workflow + biz_date 记录数据就绪时刻，维护历史基线。
-- 统计排除 TEST 实例（design D14，task 5.3）。
CREATE TABLE sla_baseline (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id          BIGINT NOT NULL,
    biz_date             VARCHAR(32) NOT NULL,
    workflow_instance_id UUID,
    ready_at             TIMESTAMP,              -- 数据就绪时刻（工作流实例 SUCCESS 完成时间）
    baseline_ready_at    TIMESTAMP,              -- 历史基线（近 N 次成功中位数）
    breached             SMALLINT DEFAULT 0,     -- 是否破线
    breach_minutes       INTEGER,                -- 破线偏差分钟数
    created_at           TIMESTAMP,
    updated_at           TIMESTAMP,
    deleted              SMALLINT DEFAULT 0,
    version              INTEGER DEFAULT 0
);

-- ============================================================
-- 域 D · 指标体系
-- ============================================================

CREATE TABLE dimensions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id  BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    code       VARCHAR(64) NOT NULL,
    name       VARCHAR(128) NOT NULL,
    data_type  VARCHAR(32),
    expr       VARCHAR(512),
    created_by BIGINT,
    updated_by BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    deleted    SMALLINT DEFAULT 0,
    version    INTEGER DEFAULT 0
);

CREATE TABLE atomic_metrics (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT NOT NULL,
    project_id    BIGINT NOT NULL,
    code          VARCHAR(64) NOT NULL,
    name          VARCHAR(128) NOT NULL,
    datasource_id BIGINT,
    source_table  VARCHAR(128),
    measure_expr  VARCHAR(1000) NOT NULL,
    agg_type      VARCHAR(32),
    unit          VARCHAR(32),
    owner_id      BIGINT,
    version_no    INTEGER NOT NULL DEFAULT 1,
    status        VARCHAR(32) DEFAULT 'ONLINE',
    created_by    BIGINT,
    updated_by    BIGINT,
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP,
    deleted       SMALLINT DEFAULT 0,
    version       INTEGER DEFAULT 0
);

CREATE TABLE derived_metrics (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id          BIGINT NOT NULL,
    project_id         BIGINT NOT NULL,
    code               VARCHAR(64) NOT NULL,
    name               VARCHAR(128) NOT NULL,
    formula            VARCHAR(1000) NOT NULL,
    atomic_refs_json   VARCHAR(1000),
    dimension_refs_json VARCHAR(1000),
    filter_expr        VARCHAR(512),
    time_window        VARCHAR(64),
    owner_id           BIGINT,
    version_no         INTEGER NOT NULL DEFAULT 1,
    status             VARCHAR(32) DEFAULT 'ONLINE',
    created_by         BIGINT,
    updated_by         BIGINT,
    created_at         TIMESTAMP,
    updated_at         TIMESTAMP,
    deleted            SMALLINT DEFAULT 0,
    version            INTEGER DEFAULT 0
);

CREATE TABLE metric_dimension (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id    BIGINT NOT NULL,
    project_id   BIGINT NOT NULL,
    metric_type  VARCHAR(32) NOT NULL,
    metric_id    BIGINT NOT NULL,
    dimension_id BIGINT NOT NULL,
    created_by   BIGINT,
    updated_by   BIGINT,
    created_at   TIMESTAMP,
    updated_at   TIMESTAMP,
    deleted      SMALLINT DEFAULT 0,
    version      INTEGER DEFAULT 0
);

CREATE TABLE metric_lineage (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT NOT NULL,
    project_id      BIGINT NOT NULL,
    metric_type     VARCHAR(32) NOT NULL,
    metric_id       BIGINT NOT NULL,
    downstream_type VARCHAR(64),
    downstream_id   VARCHAR(256),
    created_by      BIGINT,
    updated_by      BIGINT,
    created_at      TIMESTAMP,
    updated_at      TIMESTAMP,
    deleted         SMALLINT DEFAULT 0,
    version         INTEGER DEFAULT 0
);

-- ============================================================
-- 域 E · 资源与诊断
-- ============================================================

CREATE TABLE worker_nodes (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_code      VARCHAR(64) NOT NULL UNIQUE,
    host           VARCHAR(256),
    ip             VARCHAR(64),
    capacity       VARCHAR(256),
    cpu            NUMERIC(5, 2),
    mem            NUMERIC(5, 2),
    disk           NUMERIC(5, 2),
    load_avg       NUMERIC(6, 2),
    running_tasks  INTEGER,
    status         VARCHAR(32),
    max_concurrent_tasks INTEGER DEFAULT 10, -- 单节点最大并发任务数
    node_group           VARCHAR(64),        -- 节点分组（如 high-cpu / gpu）
    incarnation          BIGINT,             -- worker 启动纪元号（每次启动递增/换值；变化 → 该节点运行中实例判 WORKER_RESTART）
    reserved_test_slots  INTEGER DEFAULT 1,  -- 预留 TEST 槽数（防试跑被例行任务饿死，可配 0 关闭）
    last_heartbeat TIMESTAMP,
    created_by     BIGINT,
    updated_by     BIGINT,
    created_at     TIMESTAMP,
    updated_at     TIMESTAMP,
    deleted        SMALLINT DEFAULT 0,
    version        INTEGER DEFAULT 0
);

CREATE TABLE task_diagnosis (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id            BIGINT NOT NULL,
    project_id           BIGINT NOT NULL,
    task_instance_id     UUID,
    workflow_instance_id UUID,
    task_id              BIGINT,
    worker_node_code     VARCHAR(64),
    title                VARCHAR(256),
    root_cause           VARCHAR(2000),
    context_json         VARCHAR(4000),
    suggestions_json     VARCHAR(4000),
    status               VARCHAR(32) DEFAULT 'OPEN',
    created_by           BIGINT,
    updated_by           BIGINT,
    created_at           TIMESTAMP,
    updated_at           TIMESTAMP,
    deleted              SMALLINT DEFAULT 0,
    version              INTEGER DEFAULT 0
);

-- 通用主动发现（proactive-discovery）：Inspector→Finding 窄腰统一发现模型。
-- 任意巡检器（失败/数据质量/SLA/血缘…）产出同构 Finding，下游举手台/播报/闸门修复统一处理。
CREATE TABLE finding (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id            BIGINT NOT NULL,
    project_id           BIGINT NOT NULL,
    source               VARCHAR(32) NOT NULL,            -- TASK_FAILURE / DATA_QUALITY / SLA ...
    severity             VARCHAR(32) NOT NULL DEFAULT 'WARN', -- INFO / WARN / CRITICAL
    target_type          VARCHAR(32),                     -- TASK_INSTANCE / TABLE / WORKFLOW ...
    target_id            VARCHAR(128),                    -- 被发现对象标识（实例 UUID/表名等，统一存字符串）
    title                VARCHAR(256),
    root_cause           VARCHAR(2000),
    evidence_json        VARCHAR(4000),                   -- {nodeMem,nodeCpu,nodeLoad,concurrentTasks,history,...}
    actions_json         VARCHAR(4000),                   -- [{key,label,actionType}]
    status               VARCHAR(32) DEFAULT 'OPEN',      -- OPEN / ANNOUNCED / RESOLVED
    announced            SMALLINT DEFAULT 0,              -- 主动播报去重标记
    task_diagnosis_id    BIGINT,                          -- TASK_FAILURE 来源关联的诊断行（复用，不重写）
    created_by           BIGINT,
    updated_by           BIGINT,
    created_at           TIMESTAMP,
    updated_at           TIMESTAMP,
    deleted              SMALLINT DEFAULT 0,
    version              INTEGER DEFAULT 0
);

-- ============================================================
-- 域 F · 告警
-- ============================================================

CREATE TABLE notification_channels (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT NOT NULL,
    name        VARCHAR(128) NOT NULL,
    type        VARCHAR(32) NOT NULL,
    config_json VARCHAR(2000),
    enabled     SMALLINT DEFAULT 1,
    created_by  BIGINT,
    updated_by  BIGINT,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP,
    deleted     SMALLINT DEFAULT 0,
    version     INTEGER DEFAULT 0
);

CREATE TABLE alert_rules (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      BIGINT NOT NULL,
    project_id     BIGINT NOT NULL,
    name           VARCHAR(128) NOT NULL,
    target_type    VARCHAR(32),
    target_id      VARCHAR(64),
    condition_expr VARCHAR(512),
    level          VARCHAR(32) DEFAULT 'WARN',
    channel_id     BIGINT,
    enabled        SMALLINT DEFAULT 1,
    created_by     BIGINT,
    updated_by     BIGINT,
    created_at     TIMESTAMP,
    updated_at     TIMESTAMP,
    deleted        SMALLINT DEFAULT 0,
    version        INTEGER DEFAULT 0
);

-- ============================================================
-- 域 G · 审计与 mock 业务
-- ============================================================

CREATE TABLE audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT,
    project_id  BIGINT,
    user_id     BIGINT,
    action      VARCHAR(128),
    target_type VARCHAR(64),
    target_id   VARCHAR(64),
    detail_json VARCHAR(2000),
    created_at  TIMESTAMP
);

-- mock 业务表（供 Text-to-SQL / 指标演示）
CREATE TABLE orders (
    id           BIGINT PRIMARY KEY,
    order_amount NUMERIC(12, 2),
    city         VARCHAR(64),
    created_at   TIMESTAMP
);

-- ============================================================
-- 域 H · Agent 审计与策略（agent-fabric-m1）
--   审计四表：agent_session / agent_run / agent_step / agent_action
--   策略表：policy_rules（数据驱动 L0–L4 分级）
--   无显式 FK（与全库一致用裸 BIGINT 关联）；JSON 存 VARCHAR；枚举 VARCHAR(32)。
-- ============================================================

-- 对话 ⇄ workhorse 会话映射；mode 记录裁决路径
CREATE TABLE agent_session (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id            BIGINT,
    project_id           BIGINT,
    conversation_id      VARCHAR(128) NOT NULL,    -- AG-UI threadId
    workhorse_session_id VARCHAR(128),             -- workhorse 会话 id（mock 模式为空）
    mode                 VARCHAR(32) NOT NULL,     -- MOCK / WORKHORSE
    workspace_state      VARCHAR(8000),            -- Workspace 快照（前端序列化 JSON，后端透明 blob）
    created_by           BIGINT,
    updated_by           BIGINT,
    created_at           TIMESTAMP,
    updated_at           TIMESTAMP,
    deleted              SMALLINT DEFAULT 0,
    version              INTEGER DEFAULT 0
);

-- 自有聊天台多会话（agent-chat-shell）：用户可见的会话元数据 + 消息持久化，供前端列表/切换/重水合。
-- 与审计用的 agent_session（按 AG-UI threadId）分离：这里是面向用户的会话本体。
CREATE TABLE agent_chat_session (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id            BIGINT NOT NULL,
    project_id           BIGINT NOT NULL,
    title                VARCHAR(256),
    created_by           BIGINT,
    updated_by           BIGINT,
    created_at           TIMESTAMP,
    updated_at           TIMESTAMP,
    deleted              SMALLINT DEFAULT 0,
    version              INTEGER DEFAULT 0
);

CREATE TABLE agent_chat_message (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id           BIGINT NOT NULL,
    role                 VARCHAR(16) NOT NULL,    -- user / assistant
    parts_json           VARCHAR(8000),           -- MessagePart[] 序列化（后端透明 blob）
    created_at           TIMESTAMP
);

-- 聊天附件文件（chat-attachments）：用户在输入框上传的真实文件元数据。
-- 字节存外部存储（ChatFileStorage：Local 默认 / Minio 可选），库里只存元数据 + storage_key。
-- sha256 去重；附件引用经 forwardedProps.dataweave.attachments 透传给 Agent。
CREATE TABLE agent_chat_file (
    id                   VARCHAR(64) PRIMARY KEY,  -- sha256（内容寻址，天然去重）
    tenant_id            BIGINT NOT NULL,
    original_name        VARCHAR(512) NOT NULL,
    mime_type            VARCHAR(128),
    size_bytes           BIGINT NOT NULL,
    storage_type         VARCHAR(16) NOT NULL,     -- LOCAL / MINIO
    storage_key          VARCHAR(256) NOT NULL,
    created_by           BIGINT,
    created_at           TIMESTAMP
);

-- 一次用户触发的 agent 运行
CREATE TABLE agent_run (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   BIGINT NOT NULL,
    run_key      VARCHAR(128),                     -- AG-UI runId
    trigger_type VARCHAR(32),                      -- USER_MESSAGE / APPROVAL_CONTINUATION
    user_message VARCHAR(4000),
    state        VARCHAR(32) DEFAULT 'RUNNING',    -- RUNNING / FINISHED / FAILED
    started_at   TIMESTAMP,
    finished_at  TIMESTAMP,
    created_at   TIMESTAMP,
    updated_at   TIMESTAMP
);

-- 每次工具调用（tool_use_id 与 workhorse 事件天然 join）
CREATE TABLE agent_step (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id          BIGINT NOT NULL,
    seq             INTEGER,                        -- 运行内步骤序号
    tool_use_id     VARCHAR(128),                   -- workhorse 事件中的 tool_use_id
    tool_name       VARCHAR(128),
    input_json      VARCHAR(4000),
    output_preview  VARCHAR(4000),                  -- 截断后预览
    output_ref      VARCHAR(1000),                  -- 完整输出引用（本地文件路径，M2 迁 MinIO）
    output_bytes    INTEGER,                        -- 原始输出字节数
    truncated       SMALLINT DEFAULT 0,
    decision        VARCHAR(32),                    -- 权限决议：ALLOW / DENY
    decision_source VARCHAR(32),                    -- rule / default / prompt / timeout
    duration_ms     BIGINT,
    created_at      TIMESTAMP,
    updated_at      TIMESTAMP
);

-- 副作用操作 + 分级 + 审批生命周期（审批单即此表行的生命周期，不另设表）
CREATE TABLE agent_action (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    step_id         BIGINT,                         -- 关联 step（applyFix/CLI 来源可为空）
    policy_level    VARCHAR(8),                     -- L0..L4
    action_type     VARCHAR(64),                    -- RERUN / MIGRATE_NODE / NODE_EXEC / TASK_RERUN ...
    target_type     VARCHAR(64),                    -- TASK_INSTANCE / NODE / TASK ...
    target_id       VARCHAR(128),
    command         VARCHAR(2000),                  -- node_exec 命令串等
    summary         VARCHAR(512),                   -- 审批卡片摘要
    actor           VARCHAR(128),                   -- 操作者（agent / 用户名 / CLI token 主体）
    actor_source    VARCHAR(32),                    -- AGENT / CLI / UI
    approval_status VARCHAR(32) DEFAULT 'NONE',     -- NONE / PENDING / APPROVED / REJECTED / EXPIRED
    approved_by     VARCHAR(128),
    approved_at     TIMESTAMP,
    executed_at     TIMESTAMP,
    result_json     VARCHAR(4000),
    expires_at      TIMESTAMP,
    created_at      TIMESTAMP,
    updated_at      TIMESTAMP
);

-- 数据驱动分级规则（PolicyEngine 匹配源；宁严勿松）
CREATE TABLE policy_rules (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_type     VARCHAR(32) NOT NULL,            -- TOOL / CMD_PREFIX
    pattern        VARCHAR(128) NOT NULL,           -- 工具名 或 命令前缀
    condition_expr VARCHAR(256),                    -- 可选条件标签（NOT_OWNED / ENV_PROD / BATCH_OVER_N）
    base_level     VARCHAR(8) NOT NULL,             -- L0..L4
    description    VARCHAR(256),
    enabled        SMALLINT DEFAULT 1,
    sort_order     INTEGER DEFAULT 100,             -- 匹配优先级（小者先）
    created_by     BIGINT,
    updated_by     BIGINT,
    created_at     TIMESTAMP,
    updated_at     TIMESTAMP,
    deleted        SMALLINT DEFAULT 0,
    version        INTEGER DEFAULT 0
);

-- ============================================================
-- 域 F · 表级/任务级血缘（table-lineage：表为节点、任务为边的二部图）
-- ============================================================

-- 血缘图节点：数据表（跨数据源）。datasource_id=0 表示未知源（降级节点），
-- 用 0 而非 NULL 以保证 (datasource_id, qualified_name) 唯一约束在 H2/PG 行为一致。
CREATE TABLE data_table (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT NOT NULL,
    project_id      BIGINT NOT NULL,
    datasource_id   BIGINT NOT NULL DEFAULT 0,
    qualified_name  VARCHAR(512) NOT NULL,
    layer           VARCHAR(16),
    created_by      BIGINT,
    updated_by      BIGINT,
    created_at      TIMESTAMP,
    updated_at      TIMESTAMP,
    deleted         SMALLINT DEFAULT 0,
    version         INTEGER DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_data_table_ds_name ON data_table (datasource_id, qualified_name);
CREATE INDEX IF NOT EXISTS idx_data_table_layer ON data_table (layer);

-- 设计态血缘边：任务读/写了哪些表（建任务即写入）
CREATE TABLE task_table_io (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT NOT NULL,
    project_id      BIGINT NOT NULL,
    task_def_id     BIGINT NOT NULL,
    task_version_no INTEGER,
    table_id        BIGINT NOT NULL,
    direction       VARCHAR(8) NOT NULL,
    source          VARCHAR(16) NOT NULL,
    confidence      VARCHAR(16) NOT NULL,
    created_by      BIGINT,
    updated_by      BIGINT,
    created_at      TIMESTAMP,
    updated_at      TIMESTAMP,
    deleted         SMALLINT DEFAULT 0,
    version         INTEGER DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_task_table_io_task ON task_table_io (task_def_id);
CREATE INDEX IF NOT EXISTS idx_task_table_io_table ON task_table_io (table_id);

-- 运行态血缘边（Phase 2）：某次运行实际读/写行数与字节
CREATE TABLE task_run_table_io (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id         BIGINT NOT NULL,
    project_id        BIGINT NOT NULL,
    task_instance_id  UUID NOT NULL,
    table_id          BIGINT NOT NULL,
    direction         VARCHAR(8) NOT NULL,
    row_count         BIGINT,
    bytes             BIGINT,
    biz_date          VARCHAR(32),
    created_at        TIMESTAMP,
    deleted           SMALLINT DEFAULT 0,
    version           INTEGER DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_task_run_table_io_inst ON task_run_table_io (task_instance_id);
CREATE INDEX IF NOT EXISTS idx_task_run_table_io_bizdate ON task_run_table_io (biz_date);

-- ============================================================
-- master_nodes（cron 分片，Batch B）
-- 记录活 master 成员，供哈希分片计算「本机序号 / 活 master 数」。
-- 与 worker_nodes 同心跳惯例：自注册 + 心跳续约 + 超时剔除。
-- ============================================================
CREATE TABLE IF NOT EXISTS master_nodes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    master_code     VARCHAR(96) NOT NULL,
    master_uri      VARCHAR(256),
    incarnation     BIGINT,
    status          VARCHAR(32) NOT NULL DEFAULT 'ONLINE',
    last_heartbeat  TIMESTAMP,
    created_at      TIMESTAMP,
    updated_at      TIMESTAMP,
    CONSTRAINT uq_master_nodes_code UNIQUE (master_code)
);
CREATE INDEX IF NOT EXISTS idx_master_nodes_scan ON master_nodes (status, last_heartbeat);
