-- DataWeave schema. 兼容 PostgreSQL / H2 的通用 DDL。
-- 自增用 GENERATED BY DEFAULT AS IDENTITY；类型用 VARCHAR / BIGINT / TIMESTAMP / NUMERIC。

DROP TABLE IF EXISTS metric_lineage;
DROP TABLE IF EXISTS metrics;
DROP TABLE IF EXISTS task_instances;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS orders;

CREATE TABLE users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(128) NOT NULL,
    email    VARCHAR(256),
    role     VARCHAR(64)
);

CREATE TABLE tasks (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(256) NOT NULL,
    type       VARCHAR(64)  NOT NULL,
    content    VARCHAR(4000),
    cron       VARCHAR(128),
    status     VARCHAR(32),
    depends_on VARCHAR(256),
    created_at TIMESTAMP
);

CREATE TABLE task_instances (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id     BIGINT NOT NULL,
    state       VARCHAR(32),
    started_at  TIMESTAMP,
    finished_at TIMESTAMP,
    log         VARCHAR(4000)
);

CREATE TABLE metrics (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(128) NOT NULL,
    expr_sql     VARCHAR(1000) NOT NULL,
    source_table VARCHAR(128),
    dimensions   VARCHAR(512),
    owner        VARCHAR(128),
    version      INTEGER NOT NULL,
    created_at   TIMESTAMP
);

CREATE TABLE metric_lineage (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_id       BIGINT NOT NULL,
    downstream_type VARCHAR(64),
    downstream_id   VARCHAR(256)
);

-- mock 业务表
CREATE TABLE orders (
    id           BIGINT PRIMARY KEY,
    order_amount NUMERIC(12, 2),
    created_at   TIMESTAMP
);
