package com.dataweave.master.application.companion;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import javax.sql.DataSource;

import com.dataweave.master.companion.domain.CompanionMessage;
import com.dataweave.master.companion.domain.CompanionRoles;
import com.dataweave.master.companion.domain.PatrolDomains;
import com.dataweave.master.companion.domain.PatrolReport;
import com.dataweave.master.companion.domain.PatrolRoutine;
import com.dataweave.master.companion.domain.PatrolRun;
import com.dataweave.master.companion.domain.PatrolRunStates;
import com.dataweave.master.companion.domain.ReportSeverities;
import com.dataweave.master.companion.domain.ReportStatuses;
import com.dataweave.master.companion.infrastructure.JdbcCompanionMessageRepository;
import com.dataweave.master.companion.infrastructure.JdbcPatrolReportRepository;
import com.dataweave.master.companion.infrastructure.JdbcPatrolRoutineRepository;
import com.dataweave.master.companion.infrastructure.JdbcPatrolRunRepository;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.SingleConnectionDataSource;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * 071 Phase 2 地基测试：四仓储 CRUD/CAS/幂等/聚合。对齐 IncidentRepositoryIT 模式——
 * SingleConnectionDataSource + 隔离 H2 库（记忆：H2 共享内存库测试串台），不依赖 @SpringBootTest。
 *
 * <p>schema.sql/data.sql 在 api 模块 resources，master 测试 classpath 不可见，故内联 4 表 DDL
 * （与 schema.sql 0.21.0 同源副本）；真实 schema+data 在 H2 的全量加载由 api 模块 controller IT（T016/T021/T029）覆盖。
 */
class CompanionRepositoryIT {

    private static final long TENANT = 1L;
    private static final long PROJECT = 1L;

    private DataSource ds;
    private JdbcTemplate jdbc;
    private JdbcPatrolRoutineRepository routineRepo;
    private JdbcPatrolRunRepository runRepo;
    private JdbcPatrolReportRepository reportRepo;
    private JdbcCompanionMessageRepository messageRepo;

    @BeforeEach
    void setUp() {
        ds = new SingleConnectionDataSource(
                "jdbc:h2:mem:companion_repo_it;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;" +
                "DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE", true);
        jdbc = new JdbcTemplate(ds);
        jdbc.execute("""
                CREATE TABLE patrol_routine (
                    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id       BIGINT NOT NULL,
                    project_id      BIGINT NOT NULL,
                    domain          VARCHAR(32) NOT NULL,
                    enabled         SMALLINT NOT NULL DEFAULT 1,
                    cron_expression VARCHAR(64) NOT NULL,
                    scope_json      TEXT,
                    timeout_seconds INTEGER NOT NULL DEFAULT 120,
                    created_by      BIGINT,
                    updated_by      BIGINT,
                    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    deleted         SMALLINT NOT NULL DEFAULT 0,
                    version         INTEGER NOT NULL DEFAULT 0,
                    CONSTRAINT uk_patrol_routine_project_domain UNIQUE (project_id, domain),
                    CONSTRAINT ck_patrol_routine_domain CHECK (domain IN ('TASK_FAILURE','MACHINE','DATA_QUALITY','CODE_QUALITY'))
                )
                """);
        jdbc.execute("""
                CREATE TABLE patrol_run (
                    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id            BIGINT NOT NULL,
                    project_id           BIGINT NOT NULL,
                    routine_id           BIGINT NOT NULL,
                    trigger_type         VARCHAR(16) NOT NULL,
                    scheduled_fire_time  TIMESTAMP NOT NULL,
                    state                VARCHAR(16) NOT NULL DEFAULT 'CLAIMED',
                    started_at           TIMESTAMP,
                    finished_at          TIMESTAMP,
                    summary              TEXT,
                    error                TEXT,
                    created_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    version              INTEGER NOT NULL DEFAULT 0,
                    CONSTRAINT uk_patrol_run_routine_fire UNIQUE (routine_id, scheduled_fire_time),
                    CONSTRAINT ck_patrol_run_trigger CHECK (trigger_type IN ('SCHEDULED','MANUAL')),
                    CONSTRAINT ck_patrol_run_state CHECK (state IN ('CLAIMED','RUNNING','SUCCEEDED','FAILED','TIMEOUT'))
                )
                """);
        jdbc.execute("""
                CREATE TABLE patrol_report (
                    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id       BIGINT NOT NULL,
                    project_id      BIGINT NOT NULL,
                    run_id          BIGINT,
                    domain          VARCHAR(32) NOT NULL,
                    severity        VARCHAR(16) NOT NULL,
                    title           VARCHAR(255) NOT NULL,
                    summary         TEXT,
                    detail_json     TEXT,
                    aggregate_count INTEGER NOT NULL DEFAULT 1,
                    status          VARCHAR(16) NOT NULL DEFAULT 'UNREAD',
                    closed_by       VARCHAR(128),
                    closed_at       TIMESTAMP,
                    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT ck_patrol_report_severity CHECK (severity IN ('DANGER','WARN','OK','INFO')),
                    CONSTRAINT ck_patrol_report_status CHECK (status IN ('UNREAD','READ','CLOSED')),
                    CONSTRAINT ck_patrol_report_domain CHECK (domain IN ('TASK_FAILURE','MACHINE','DATA_QUALITY','CODE_QUALITY'))
                )
                """);
        jdbc.execute("""
                CREATE TABLE companion_message (
                    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id        BIGINT NOT NULL,
                    project_id       BIGINT NOT NULL,
                    report_id        BIGINT,
                    role             VARCHAR(16) NOT NULL,
                    actor            VARCHAR(64),
                    actor_name       VARCHAR(128),
                    content          TEXT,
                    brain_session_id VARCHAR(128),
                    created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT ck_companion_message_role CHECK (role IN ('USER','AGENT','SYSTEM'))
                )
                """);
        routineRepo = new JdbcPatrolRoutineRepository(jdbc);
        runRepo = new JdbcPatrolRunRepository(jdbc);
        reportRepo = new JdbcPatrolReportRepository(jdbc);
        messageRepo = new JdbcCompanionMessageRepository(jdbc);
        // 种 4 领域例程（仿 data.sql seed，供多数测试复用）
        seedRoutine(PatrolDomains.TASK_FAILURE, "0 */15 * * * *");
        seedRoutine(PatrolDomains.MACHINE, "0 */30 * * * *");
        seedRoutine(PatrolDomains.DATA_QUALITY, "0 0 * * * *");
        seedRoutine(PatrolDomains.CODE_QUALITY, "0 0 2 * * *");
    }

    private void seedRoutine(String domain, String cron) {
        routineRepo.insert(TENANT, PROJECT, domain, true, cron, null, 120, 1L);
    }

    @AfterEach
    void tearDown() {
        jdbc.execute("DROP ALL OBJECTS");
        ((SingleConnectionDataSource) ds).destroy();
    }

    // ===== PatrolRoutine =====

    @Test
    void routines_findByProjectAndDomainAndAllEnabled() {
        List<PatrolRoutine> routines = routineRepo.findByProject(TENANT, PROJECT);
        assertThat(routines).hasSize(4);
        assertThat(routines).allSatisfy(r -> {
            assertThat(r.enabled()).isTrue();
            assertThat(r.timeoutSeconds()).isEqualTo(120);
        });
        assertThat(routines).extracting(PatrolRoutine::domain).containsExactlyInAnyOrder(
                PatrolDomains.TASK_FAILURE, PatrolDomains.MACHINE,
                PatrolDomains.DATA_QUALITY, PatrolDomains.CODE_QUALITY);
        Optional<PatrolRoutine> tf = routineRepo.findByProjectAndDomain(TENANT, PROJECT, PatrolDomains.TASK_FAILURE);
        assertThat(tf).isPresent();
        assertThat(tf.get().cronExpression()).isEqualTo("0 */15 * * * *");
        assertThat(routineRepo.findAllEnabled()).hasSize(4);
    }

    @Test
    void routineUpdate_optimisticVersionLock() {
        PatrolRoutine r = routineRepo.findByProjectAndDomain(TENANT, PROJECT, PatrolDomains.MACHINE).orElseThrow();
        int v0 = r.version();

        assertThat(routineRepo.update(r.id(), TENANT, PROJECT, false, r.cronExpression(), r.scopeJson(), 1L, v0 + 99))
                .isFalse();
        assertThat(routineRepo.update(r.id(), TENANT, PROJECT, false, "0 0 * * * *", null, 1L, v0)).isTrue();

        PatrolRoutine after = routineRepo.findById(r.id()).orElseThrow();
        assertThat(after.enabled()).isFalse();
        assertThat(after.cronExpression()).isEqualTo("0 0 * * * *");
        assertThat(after.version()).isEqualTo(v0 + 1);
    }

    @Test
    void routineInsert_duplicateDomainConflicts() {
        // UNIQUE(project_id, domain) 冲突 → 抛 DuplicateKeyException（未 catch，测试断言异常）
        org.assertj.core.api.Assertions.assertThatThrownBy(() ->
                        routineRepo.insert(TENANT, PROJECT, PatrolDomains.MACHINE, true, "0 0 * * * *", null, 60, 1L))
                .isInstanceOf(org.springframework.dao.DuplicateKeyException.class);
    }

    // ===== PatrolRun（幂等 arm + SKIP LOCKED claim + CAS + reaper）=====

    @Test
    void tryClaimCreate_idempotentSameFireTime() {
        long routineId = routineIdOf(PatrolDomains.TASK_FAILURE);
        LocalDateTime fire = LocalDateTime.of(2026, 7, 15, 9, 0);

        Optional<PatrolRun> first = runRepo.tryClaimCreate(TENANT, PROJECT, routineId, "SCHEDULED", fire);
        assertThat(first).isPresent();
        assertThat(first.get().state()).isEqualTo(PatrolRunStates.CLAIMED);

        Optional<PatrolRun> second = runRepo.tryClaimCreate(TENANT, PROJECT, routineId, "SCHEDULED", fire);
        assertThat(second).isEmpty();
    }

    @Test
    void claimLifecycle_claimedToRunningToSucceeded() {
        long routineId = routineIdOf(PatrolDomains.MACHINE);
        LocalDateTime fire = LocalDateTime.of(2026, 7, 15, 9, 30);
        runRepo.tryClaimCreate(TENANT, PROJECT, routineId, "SCHEDULED", fire);

        List<PatrolRun> claimed = runRepo.pollClaimed(10);
        assertThat(claimed).hasSize(1);
        long runId = claimed.get(0).id();

        assertThat(runRepo.casStart(999999L)).isFalse();
        assertThat(runRepo.casStart(runId)).isTrue();
        assertThat(runRepo.existsRunningInProject(TENANT, PROJECT)).isTrue();

        assertThat(runRepo.casFinish(runId, PatrolRunStates.SUCCEEDED, "all green", null)).isTrue();
        PatrolRun done = runRepo.findById(runId).orElseThrow();
        assertThat(done.state()).isEqualTo(PatrolRunStates.SUCCEEDED);
        assertThat(done.summary()).isEqualTo("all green");
        assertThat(done.finishedAt()).isNotNull();
        // 已终态再 casFinish 失败
        assertThat(runRepo.casFinish(runId, PatrolRunStates.FAILED, "x", null)).isFalse();
    }

    @Test
    void reaper_findsRunningCandidatesAndMarksTimeout() {
        long routineId = routineIdOf(PatrolDomains.CODE_QUALITY);
        PatrolRun run = runRepo.tryClaimCreate(TENANT, PROJECT, routineId, "SCHEDULED", LocalDateTime.now()).orElseThrow();
        assertThat(runRepo.casStart(run.id())).isTrue();

        List<JdbcPatrolRunRepository.RunningRun> candidates = runRepo.findRunningCandidates();
        assertThat(candidates).isNotEmpty();
        JdbcPatrolRunRepository.RunningRun self = candidates.stream()
                .filter(c -> c.id() == run.id()).findFirst().orElseThrow();
        assertThat(self.timeoutSeconds()).isEqualTo(120);
        assertThat(self.startedAt()).isNotNull();

        assertThat(runRepo.markTimeout(run.id(), "brain 120s 超时")).isTrue();
        assertThat(runRepo.findById(run.id()).orElseThrow().state()).isEqualTo(PatrolRunStates.TIMEOUT);
    }

    @Test
    void countToday_countsRunsCreatedSinceCutoff() {
        long routineId = routineIdOf(PatrolDomains.DATA_QUALITY);
        runRepo.tryClaimCreate(TENANT, PROJECT, routineId, "MANUAL", LocalDateTime.now());
        assertThat(runRepo.countToday(TENANT, PROJECT, LocalDateTime.now().minusDays(1))).isGreaterThanOrEqualTo(1);
        assertThat(runRepo.findByRoutine(routineId, 10)).hasSize(1);
    }

    // ===== PatrolReport（项目级共享关闭幂等 + 异常计数）=====

    @Test
    void report_closeIsProjectLevelIdempotentAndAnomalyCount() {
        long runId = runRepo.tryClaimCreate(TENANT, PROJECT, routineIdOf(PatrolDomains.TASK_FAILURE),
                "SCHEDULED", LocalDateTime.now()).orElseThrow().id();
        long danger = reportRepo.insert(TENANT, PROJECT, runId, PatrolDomains.TASK_FAILURE,
                ReportSeverities.DANGER, "3 个任务失败", "ETL 链路三连失败", "{}", 3);
        reportRepo.insert(TENANT, PROJECT, runId, PatrolDomains.TASK_FAILURE,
                ReportSeverities.OK, "机器正常", "无异常", "{}", 1);

        assertThat(reportRepo.existsOpenAnomaly(TENANT, PROJECT)).isTrue();
        assertThat(reportRepo.countOpenAnomalies(TENANT, PROJECT)).isEqualTo(1);
        assertThat(reportRepo.findOpenByProject(TENANT, PROJECT, 10)).hasSize(2);

        assertThat(reportRepo.close(danger, TENANT, PROJECT, "admin")).isTrue();
        assertThat(reportRepo.close(danger, TENANT, PROJECT, "admin")).isFalse(); // 已关闭
        PatrolReport closed = reportRepo.findById(danger).orElseThrow();
        assertThat(closed.status()).isEqualTo(ReportStatuses.CLOSED);
        assertThat(closed.closedBy()).isEqualTo("admin");
        assertThat(reportRepo.countOpenAnomalies(TENANT, PROJECT)).isZero();
        assertThat(reportRepo.existsOpenAnomaly(TENANT, PROJECT)).isFalse();
        assertThat(reportRepo.findByRun(runId)).hasSize(2);
    }

    @Test
    void report_markRead_unreadToRead() {
        long r = reportRepo.insert(TENANT, PROJECT, null, PatrolDomains.MACHINE,
                ReportSeverities.WARN, "节点离线", "node-2 心跳过期", "{}", 1);
        assertThat(reportRepo.findById(r).orElseThrow().status()).isEqualTo(ReportStatuses.UNREAD);
        assertThat(reportRepo.markRead(r, TENANT, PROJECT)).isTrue();
        assertThat(reportRepo.findById(r).orElseThrow().status()).isEqualTo(ReportStatuses.READ);
        assertThat(reportRepo.markRead(r, TENANT, PROJECT)).isFalse();
    }

    // ===== CompanionMessage（全局 vs 锚定会话 + brain session 续聊）=====

    @Test
    void messages_globalVsAnchoredSessionAndBrainSessionResume() {
        long g1 = messageRepo.insert(TENANT, PROJECT, null, CompanionRoles.USER, "admin", "管理员", "你好 Vega", null);
        messageRepo.insert(TENANT, PROJECT, null, CompanionRoles.AGENT, "companion-agent", "Vega",
                "系统一切正常", "sess-global-1");
        messageRepo.insert(TENANT, PROJECT, 5L, CompanionRoles.USER, "admin", "管理员", "这个失败怎么处理", null);
        messageRepo.insert(TENANT, PROJECT, 5L, CompanionRoles.AGENT, "companion-agent", "Vega",
                "建议重跑", "sess-rpt5-1");

        List<CompanionMessage> global = messageRepo.findByProject(TENANT, PROJECT, null, null, 50);
        assertThat(global).hasSize(2).extracting(CompanionMessage::id).contains(g1);
        assertThat(global).allSatisfy(m -> assertThat(m.reportId()).isNull());

        List<CompanionMessage> anchored = messageRepo.findByProject(TENANT, PROJECT, 5L, null, 50);
        assertThat(anchored).hasSize(2);
        assertThat(anchored).allSatisfy(m -> assertThat(m.reportId()).isEqualTo(5L));

        assertThat(messageRepo.findLatestBrainSession(TENANT, PROJECT, null)).contains("sess-global-1");
        assertThat(messageRepo.findLatestBrainSession(TENANT, PROJECT, 5L)).contains("sess-rpt5-1");
        assertThat(messageRepo.findLatestBrainSession(TENANT, PROJECT, 999L)).isEmpty();
    }

    private long routineIdOf(String domain) {
        return routineRepo.findByProjectAndDomain(TENANT, PROJECT, domain)
                .orElseThrow(() -> new IllegalStateException("缺例程: " + domain)).id();
    }
}
