-- ============================================================
-- task-workflow-catalog · 向后兼容迁移（PostgreSQL）
-- 类目树 + 标签：catalog_node / tag / entity_tag 三表 + 两表加 catalog_node_id 列
-- ------------------------------------------------------------
-- 全部 CREATE TABLE IF NOT EXISTS / ADD COLUMN IF NOT EXISTS，向后兼容：
--   既有任务/工作流 catalog_node_id 取默认 NULL → 自动归入「未分类」，无需回填。
-- 与兄弟变更 task-core-capabilities 改同表互不依赖加载顺序，谁先归档都不冲突。
-- 开发态（H2）由 schema.sql 重建即可，本脚本仅供 PG 环境手工执行。
-- ============================================================

BEGIN;

-- 1) 文件夹类目树（邻接表 parent_id + 物化路径 path）
CREATE TABLE IF NOT EXISTS catalog_node (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT NOT NULL,
    project_id  BIGINT NOT NULL,
    parent_id   BIGINT,
    name        VARCHAR(256) NOT NULL,
    path        VARCHAR(2000) NOT NULL,
    sort_order  INTEGER,
    created_by  BIGINT,
    updated_by  BIGINT,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP,
    deleted     SMALLINT DEFAULT 0,
    version     INTEGER DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_catalog_node_parent ON catalog_node (parent_id);
CREATE INDEX IF NOT EXISTS idx_catalog_node_path ON catalog_node (path);
CREATE INDEX IF NOT EXISTS idx_catalog_node_project ON catalog_node (project_id);

-- 2) 标签
CREATE TABLE IF NOT EXISTS tag (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT NOT NULL,
    project_id  BIGINT NOT NULL,
    name        VARCHAR(128) NOT NULL,
    color       VARCHAR(32),
    created_by  BIGINT,
    updated_by  BIGINT,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_tag_project_name ON tag (project_id, name);

-- 3) 标签-资产 多态多对多
CREATE TABLE IF NOT EXISTS entity_tag (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_id      BIGINT NOT NULL,
    entity_type VARCHAR(16) NOT NULL,
    entity_id   BIGINT NOT NULL,
    created_at  TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_entity_tag ON entity_tag (tag_id, entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_entity_tag_entity ON entity_tag (entity_type, entity_id);

-- 4) 任务/工作流加归属列（加在表尾，与 task-core-capabilities 加列互不撞行）
ALTER TABLE task_def     ADD COLUMN IF NOT EXISTS catalog_node_id BIGINT;
ALTER TABLE workflow_def ADD COLUMN IF NOT EXISTS catalog_node_id BIGINT;
CREATE INDEX IF NOT EXISTS idx_task_def_catalog ON task_def (catalog_node_id);
CREATE INDEX IF NOT EXISTS idx_workflow_def_catalog ON workflow_def (catalog_node_id);

COMMIT;
