-- ============================================================
-- datasource-driver-isolation · 向后兼容迁移（PostgreSQL）
-- 驱动 jar 资产 + 数据源绑定列：driver_jars 表 + datasources.driver_jar_id
-- ------------------------------------------------------------
-- 全部 CREATE TABLE IF NOT EXISTS / ADD COLUMN IF NOT EXISTS，向后兼容：
--   既有数据源 driver_jar_id 默认 NULL → 走内置默认驱动，无需回填。
-- 开发态（H2）由 schema.sql 重建即可，本脚本仅供 PG 环境手工执行。
-- ============================================================

BEGIN;

-- 1) 驱动 jar 资产（按 tenant + sha256 去重，可被多数据源复用）
CREATE TABLE IF NOT EXISTS driver_jars (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT NOT NULL,
    type_code     VARCHAR(64) NOT NULL,
    driver_class  VARCHAR(256),
    original_name VARCHAR(256),
    sha256        VARCHAR(64) NOT NULL,
    storage_type  VARCHAR(16),
    storage_key   VARCHAR(512),
    size_bytes    BIGINT,
    status        VARCHAR(32) DEFAULT 'PENDING',
    created_by    BIGINT,
    updated_by    BIGINT,
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP,
    deleted       SMALLINT DEFAULT 0,
    version       INTEGER DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_driver_jars_tenant_sha ON driver_jars (tenant_id, sha256);
CREATE INDEX IF NOT EXISTS idx_driver_jars_type ON driver_jars (type_code);

-- 2) 数据源绑定上传驱动 jar（NULL = 走内置默认驱动，向后兼容）
ALTER TABLE datasources ADD COLUMN IF NOT EXISTS driver_jar_id BIGINT;
CREATE INDEX IF NOT EXISTS idx_datasources_driver_jar ON datasources (driver_jar_id);

COMMIT;
