-- ============================================================
-- V__add-master-nodes · 向后兼容迁移（PostgreSQL）
-- 新增 master_nodes 表 + 索引，支撑 cron 分片（Batch B）
-- ------------------------------------------------------------
-- 记录活 master 成员，供哈希分片计算「本机序号 / 活 master 数」。
-- 与 worker_nodes 同心跳惯例：自注册 + 心跳续约 + 超时剔除。
-- 开发态（H2）由 schema.sql 重建即可，本脚本仅供 PG 环境手工执行。
-- ============================================================

BEGIN;

CREATE TABLE IF NOT EXISTS master_nodes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    master_code     VARCHAR(96) NOT NULL,
    master_uri      VARCHAR(256),
    incarnation     BIGINT,
    status          VARCHAR(32) NOT NULL DEFAULT 'ONLINE',
    last_heartbeat  TIMESTAMP,
    created_at      TIMESTAMP,
    updated_at      TIMESTAMP,
    CONSTRAINT uq_master_nodes_code UNIQUE (master_code)
);

CREATE INDEX IF NOT EXISTS idx_master_nodes_scan
    ON master_nodes (status, last_heartbeat);

COMMIT;
