package com.dataweave.alert.application;

import com.dataweave.alert.domain.HealthEvent;
import com.dataweave.alert.domain.repository.AlertChannelRepository;
import com.dataweave.alert.domain.repository.EventSubscriptionRepository;
import com.dataweave.alert.infrastructure.jdbc.HealthEventJdbcRepository;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabase;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;

import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.mock;

/**
 * 027 US1：EventCenterService.query —— 过滤 + 租户隔离（H2 独立库）。
 */
class EventCenterServiceQueryTest {

    private EmbeddedDatabase db;
    private EventCenterService service;

    @BeforeEach
    void setUp() {
        db = new EmbeddedDatabaseBuilder()
                .setType(EmbeddedDatabaseType.H2).generateUniqueName(true).build();
        JdbcTemplate jdbc = new JdbcTemplate(db);
        jdbc.execute("""
                CREATE TABLE health_event (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id BIGINT NOT NULL, type VARCHAR(32) NOT NULL, severity VARCHAR(16),
                    fingerprint VARCHAR(128) NOT NULL, ref_kind VARCHAR(16), ref_id VARCHAR(128), ref_name VARCHAR(256),
                    summary VARCHAR(512), context_json VARCHAR(2000), count INTEGER DEFAULT 1,
                    first_occurred_at TIMESTAMP, last_occurred_at TIMESTAMP, created_at TIMESTAMP, deleted SMALLINT DEFAULT 0
                )""");
        jdbc.execute("CREATE UNIQUE INDEX uk_health_event_dedup ON health_event (tenant_id, type, fingerprint)");
        HealthEventJdbcRepository repo = new HealthEventJdbcRepository(jdbc);
        service = new EventCenterService(repo, mock(EventSubscriptionRepository.class),
                mock(AlertChannelRepository.class), mock(AlertDispatchService.class));

        repo.record(ev(10L, "SLA_BREACH", "HIGH", "fp-a"));
        repo.record(ev(10L, "QUALITY_FAILED", "MEDIUM", "fp-b"));
        repo.record(ev(20L, "SLA_BREACH", "HIGH", "fp-c")); // 另一租户
    }

    @AfterEach
    void tearDown() { db.shutdown(); }

    private HealthEvent ev(long tenant, String type, String sev, String fp) {
        HealthEvent e = new HealthEvent();
        e.setTenantId(tenant); e.setType(type); e.setSeverity(sev); e.setFingerprint(fp);
        return e;
    }

    @Test
    @SuppressWarnings("unchecked")
    void query_isolates_by_tenant() {
        Map<String, Object> data = service.query(10L, null, null, null, null, null, null, false, 0, 20);
        assertThat((int) data.get("total")).isEqualTo(2); // 仅租户 10 的两条
        List<HealthEvent> items = (List<HealthEvent>) data.get("items");
        assertThat(items).extracting(HealthEvent::getTenantId).containsOnly(10L);
    }

    @Test
    @SuppressWarnings("unchecked")
    void query_filters_by_type() {
        Map<String, Object> data = service.query(10L, "QUALITY_FAILED", null, null, null, null, null, false, 0, 20);
        assertThat((int) data.get("total")).isEqualTo(1);
        List<HealthEvent> items = (List<HealthEvent>) data.get("items");
        assertThat(items.get(0).getType()).isEqualTo("QUALITY_FAILED");
    }
}
