package com.dataweave.alert.application;

import com.dataweave.alert.infrastructure.jdbc.HealthEventJdbcRepository;
import com.dataweave.master.domain.signal.AlertSignal;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabase;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;

import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.mock;

/**
 * 027 US1：HealthEventRecorder 把信号旁路持久化；同 (tenant,type,fingerprint) 重复 → count 递增不新增。
 */
class HealthEventRecorderTest {

    private EmbeddedDatabase db;
    private JdbcTemplate jdbc;
    private HealthEventRecorder recorder;

    @BeforeEach
    void setUp() {
        db = new EmbeddedDatabaseBuilder()
                .setType(EmbeddedDatabaseType.H2).generateUniqueName(true).build();
        jdbc = new JdbcTemplate(db);
        jdbc.execute("""
                CREATE TABLE health_event (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id BIGINT NOT NULL, type VARCHAR(32) NOT NULL, severity VARCHAR(16),
                    fingerprint VARCHAR(128) NOT NULL, ref_kind VARCHAR(16), ref_id VARCHAR(128), ref_name VARCHAR(256),
                    summary VARCHAR(512), context_json VARCHAR(2000), count INTEGER DEFAULT 1,
                    first_occurred_at TIMESTAMP, last_occurred_at TIMESTAMP, created_at TIMESTAMP, deleted SMALLINT DEFAULT 0
                )""");
        jdbc.execute("CREATE UNIQUE INDEX uk_health_event_dedup ON health_event (tenant_id, type, fingerprint)");
        HealthEventJdbcRepository repo = new HealthEventJdbcRepository(jdbc);
        // matchAndDispatch 无关本测试 → mock 掉
        EventCenterService svc = mock(EventCenterService.class);
        recorder = new HealthEventRecorder(repo, svc);
    }

    @AfterEach
    void tearDown() { db.shutdown(); }

    private AlertSignal signal() {
        return new AlertSignal(AlertSignal.Type.QUALITY_FAILED, 10L, "db.orders", "HIGH",
                Map.of("datasetRef", "db.orders", "message", "null rate 0.83"));
    }

    @Test
    void records_health_event_from_signal() {
        recorder.onSignal(signal());

        var rows = jdbc.queryForList("SELECT * FROM health_event WHERE tenant_id = 10");
        assertThat(rows).hasSize(1);
        Map<String, Object> r = rows.get(0);
        assertThat(r.get("TYPE")).isEqualTo("QUALITY_FAILED");
        assertThat(r.get("SEVERITY")).isEqualTo("HIGH");
        assertThat(r.get("REF_KIND")).isEqualTo("TABLE");   // datasetRef → TABLE
        assertThat(r.get("REF_ID")).isEqualTo("db.orders");
        assertThat(((Number) r.get("COUNT")).intValue()).isEqualTo(1);
    }

    @Test
    void dedupes_repeated_signal_incrementing_count() {
        recorder.onSignal(signal());
        recorder.onSignal(signal());
        recorder.onSignal(signal());

        var rows = jdbc.queryForList("SELECT count FROM health_event WHERE tenant_id = 10");
        assertThat(rows).hasSize(1); // 仍 1 行
        assertThat(((Number) rows.get(0).get("COUNT")).intValue()).isEqualTo(3);
    }
}
