package com.dataweave.api.infrastructure;

import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.SingleConnectionDataSource;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * CriticalSeedReifier 单元测试：H2 内存库验证补灌逻辑（缺→补、已存在→跳过幂等、跨方言）。
 * 模拟 docker 旧库缺 data.sql 后续 seed 的场景。
 */
class CriticalSeedReifierTest {

    /** 建一张空白的 policy_rules + patrol_routine（模拟旧库表已建但 seed 缺失）。 */
    private JdbcTemplate freshDb() {
        SingleConnectionDataSource ds = new SingleConnectionDataSource();
        ds.setDriverClassName("org.h2.Driver");
        ds.setUrl("jdbc:h2:mem:seedreify-" + System.nanoTime());
        ds.setUsername("sa");
        ds.setPassword("");
        ds.setSuppressClose(true);   // 单一连接不断 → H2 mem 库随之保持，避免连接切换致库关闭
        JdbcTemplate jdbc = new JdbcTemplate(ds);
        jdbc.execute("""
                CREATE TABLE policy_rules (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    match_type VARCHAR(32) NOT NULL,
                    pattern VARCHAR(128) NOT NULL,
                    condition_expr VARCHAR(256),
                    base_level VARCHAR(8) NOT NULL,
                    description VARCHAR(256),
                    enabled SMALLINT DEFAULT 1,
                    sort_order INTEGER DEFAULT 100,
                    created_by BIGINT,
                    updated_by BIGINT,
                    created_at TIMESTAMP,
                    updated_at TIMESTAMP,
                    deleted SMALLINT DEFAULT 0,
                    version INTEGER DEFAULT 0
                )""");
        jdbc.execute("""
                CREATE TABLE patrol_routine (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id BIGINT NOT NULL,
                    project_id BIGINT NOT NULL,
                    domain VARCHAR(32) NOT NULL,
                    enabled SMALLINT NOT NULL DEFAULT 1,
                    cron_expression VARCHAR(64) NOT NULL,
                    scope_json TEXT,
                    timeout_seconds INTEGER NOT NULL DEFAULT 120,
                    created_by BIGINT,
                    updated_by BIGINT,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    deleted SMALLINT NOT NULL DEFAULT 0,
                    version INTEGER NOT NULL DEFAULT 0,
                    CONSTRAINT uk_patrol_routine_project_domain UNIQUE (project_id, domain),
                    CONSTRAINT ck_patrol_routine_domain CHECK (domain IN ('TASK_FAILURE','MACHINE','DATA_QUALITY','CODE_QUALITY'))
                )""");
        return jdbc;
    }

    private int ruleCount(JdbcTemplate jdbc) {
        Integer n = jdbc.queryForObject("SELECT count(*) FROM policy_rules WHERE deleted = 0", Integer.class);
        return n == null ? 0 : n;
    }

    private int routineCount(JdbcTemplate jdbc) {
        Integer n = jdbc.queryForObject("SELECT count(*) FROM patrol_routine WHERE deleted = 0", Integer.class);
        return n == null ? 0 : n;
    }

    @Test
    void reifiesAllOnEmptyDb_thenIdempotent() {
        JdbcTemplate jdbc = freshDb();
        CriticalSeedReifier reifier = new CriticalSeedReifier(jdbc);

        reifier.run();
        assertThat(ruleCount(jdbc)).isEqualTo(7);     // 6 incident + 1 companion
        assertThat(routineCount(jdbc)).isEqualTo(4);  // 四领域

        // 幂等：再跑不重复补
        reifier.run();
        assertThat(ruleCount(jdbc)).isEqualTo(7);
        assertThat(routineCount(jdbc)).isEqualTo(4);
    }

    @Test
    void onlyReifiesMissing_whenPartiallyPrefilled() {
        JdbcTemplate jdbc = freshDb();
        // 模拟旧库：已有 incident_rerun + incident_publish_fix + TASK_FAILURE 例程（其余缺）
        jdbc.update("INSERT INTO policy_rules (match_type, pattern, base_level, enabled, sort_order, deleted, version) "
                + "VALUES ('TOOL','incident_rerun','L1',1,20,0,0)");
        jdbc.update("INSERT INTO policy_rules (match_type, pattern, base_level, enabled, sort_order, deleted, version) "
                + "VALUES ('TOOL','incident_publish_fix','L3',1,30,0,0)");
        jdbc.update("INSERT INTO patrol_routine (tenant_id, project_id, domain, enabled, cron_expression, timeout_seconds, deleted, version) "
                + "VALUES (1,1,'TASK_FAILURE',1,'0 */15 * * * *',120,0,0)");

        new CriticalSeedReifier(jdbc).run();

        // 已有的不重复
        assertThat(jdbc.queryForObject(
                "SELECT count(*) FROM policy_rules WHERE pattern='incident_rerun' AND deleted=0", Integer.class)).isEqualTo(1);
        assertThat(jdbc.queryForObject(
                "SELECT count(*) FROM policy_rules WHERE pattern='incident_publish_fix' AND deleted=0", Integer.class)).isEqualTo(1);
        // 缺的补齐到 7 / 4
        assertThat(ruleCount(jdbc)).isEqualTo(7);
        assertThat(routineCount(jdbc)).isEqualTo(4);
    }

    @Test
    void softDeletedDoesNotBlockActiveReify() {
        JdbcTemplate jdbc = freshDb();
        // incident_rerun 被 soft-delete（deleted=1）——旧库可能的历史状态
        jdbc.update("INSERT INTO policy_rules (match_type, pattern, base_level, enabled, sort_order, deleted, version) "
                + "VALUES ('TOOL','incident_rerun','L1',1,20,1,0)");

        new CriticalSeedReifier(jdbc).run();

        // reifier 查 deleted=0，soft-deleted 不算存在 → 补一条 active 的
        assertThat(jdbc.queryForObject(
                "SELECT count(*) FROM policy_rules WHERE pattern='incident_rerun' AND deleted=0", Integer.class)).isEqualTo(1);
    }
}
